export type {
  BaselineApplicationResult,
  BaselineAuthorityProjection,
  BaselineAuthorityState,
  BaselineContractContext,
  BaselineContractValidation,
  BaselineExpansionDecision,
  BaselineIntegrityFinding,
  BaselineIntegrityResult,
  BaselineRefusal,
  BaselineRefusalReason,
  BaselineRuleContractInput,
  ExternalExceptionSource,
  RuleIntroductionBaselineManifest,
} from "./baseline-core/index.js";

export {
  applyBaseline,
  baselineAuthorityProjection,
  baselineFailureDiagnostic,
  baselineIntegrityFindings,
  baselinePath,
  checkBaselineIntegrity,
  guardBaselineExpansion,
  isBaselineLocked,
  loadBaseline,
  loadBaselineState,
  mergeBase,
  validateBaselineContract,
  violationKey,
  writeBaseline,
} from "./baseline-core/index.js";

export {
  BaselineApplicationResultSchema,
  BaselineAuthorityProjectionSchema,
  BaselineAuthorityStateSchema,
  BaselineExpansionDecisionSchema,
  BaselineIntegrityFindingSchema,
  BaselineIntegrityResultSchema,
  BaselineRuleContractInputSchema,
  BaselineRefusalReasonSchema,
  BaselineRefusalSchema,
  ExternalExceptionSourceSchema,
  RuleIntroductionBaselineManifestSchema,
} from "./baseline-core/index.js";
