/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: `bun scripts/civ7-map-policy/generate-tables.ts`
 * Source evidence: Civ7 official resource XML/JS under `.civ7/outputs/resources`,
 * plus live/runtime river evidence listed in `riverTypes.source`
 * Submodule commit: fbc38ef8a041d469cad3800011074379ccd5a179
 * Snapshot dated 2026-01-24 — refreshing requires the game install
 * (`bun run refresh:data`); flagged user follow-up (refactor-plan D4).
 *
 * Purpose:
 * - Provide Civ7-derived terrain/biome/feature indices and river metadata for mock generation.
 * - Keep browser Studio, diagnostics, and adapter mocks on the same GameInfo order.
 * - V1 adds resource weights/hemisphere minimums/required-for-age data,
 *   MapResourceMinimumAmountModifier rows, StartBias tables, and start-buffer
 *   globals for policy-grounded placement planning.
 */

export const CIV7_BROWSER_TABLES_V0 = {
  version: 0 as const,
  source: [
  "Base/modules/base-standard/data/terrain.xml",
  "Base/modules/base-standard/maps/map-globals.js",
  "Base/modules/base-standard/data/racetowonders-terrain.xml",
  "Base/modules/base-standard/data/marvelous-mountains-terrain.xml",
  "DLC/mountain-natural-wonders/modules/data/terrain.xml",
  "DLC/water-wonders/modules/data/terrain.xml",
  "Base/modules/base-standard/data/resources.xml",
  "Base/modules/base-standard/data/resources-v2.xml"
] as const,
  mapGlobals: {
  "polarWaterRows": 2,
  "oceanWaterColumns": 4
} as const,
  terrainTypeIndices: {
  "TERRAIN_COAST": 3,
  "TERRAIN_FLAT": 2,
  "TERRAIN_HILL": 1,
  "TERRAIN_MOUNTAIN": 0,
  "TERRAIN_NAVIGABLE_RIVER": 5,
  "TERRAIN_OCEAN": 4,
} as const,
  biomeGlobals: {
  "BIOME_DESERT": 4,
  "BIOME_GRASSLAND": 1,
  "BIOME_MARINE": 5,
  "BIOME_PLAINS": 2,
  "BIOME_TROPICAL": 3,
  "BIOME_TUNDRA": 0,
} as const,
  featureTypes: {
  "FEATURE_ATOLL": 27,
  "FEATURE_BARRIER_REEF": 29,
  "FEATURE_BERMUDA_TRIANGLE": 0,
  "FEATURE_COLD_REEF": 11,
  "FEATURE_DESERT_FLOODPLAIN_MINOR": 4,
  "FEATURE_DESERT_FLOODPLAIN_NAVIGABLE": 5,
  "FEATURE_FOREST": 6,
  "FEATURE_GRAND_CANYON": 31,
  "FEATURE_GRASSLAND_FLOODPLAIN_MINOR": 8,
  "FEATURE_GRASSLAND_FLOODPLAIN_NAVIGABLE": 9,
  "FEATURE_GREAT_BLUE_HOLE": 44,
  "FEATURE_GULLFOSS": 32,
  "FEATURE_HOERIKWAGGO": 33,
  "FEATURE_ICE": 12,
  "FEATURE_IGUAZU_FALLS": 34,
  "FEATURE_KILIMANJARO": 35,
  "FEATURE_LOTUS": 26,
  "FEATURE_MACHAPUCHARE": 40,
  "FEATURE_MANGROVE": 18,
  "FEATURE_MAPU_A_VAEA_BLOWHOLES": 45,
  "FEATURE_MARSH": 7,
  "FEATURE_MOUNT_EVEREST": 1,
  "FEATURE_MOUNT_FUJI": 41,
  "FEATURE_OASIS": 3,
  "FEATURE_PLAINS_FLOODPLAIN_MINOR": 15,
  "FEATURE_PLAINS_FLOODPLAIN_NAVIGABLE": 16,
  "FEATURE_RAINFOREST": 17,
  "FEATURE_REDWOOD_FOREST": 30,
  "FEATURE_REEF": 10,
  "FEATURE_SAGEBRUSH_STEPPE": 2,
  "FEATURE_SAVANNA_WOODLAND": 13,
  "FEATURE_TAIGA": 21,
  "FEATURE_THERA": 37,
  "FEATURE_TORRES_DEL_PAINE": 38,
  "FEATURE_TROPICAL_FLOODPLAIN_MINOR": 19,
  "FEATURE_TROPICAL_FLOODPLAIN_NAVIGABLE": 20,
  "FEATURE_TUNDRA_BOG": 22,
  "FEATURE_TUNDRA_FLOODPLAIN_MINOR": 23,
  "FEATURE_TUNDRA_FLOODPLAIN_NAVIGABLE": 24,
  "FEATURE_ULURU": 39,
  "FEATURE_VALLEY_OF_FLOWERS": 28,
  "FEATURE_VIHREN": 42,
  "FEATURE_VINICUNCA": 43,
  "FEATURE_VOLCANO": 25,
  "FEATURE_WATERING_HOLE": 14,
  "FEATURE_ZHANGJIAJIE": 36,
} as const,
  featureValidTerrainTypeIndices: {
  "0": [4],
  "1": [0],
  "2": [2],
  "3": [2],
  "4": [2],
  "5": [5],
  "6": [2],
  "7": [2],
  "8": [2],
  "9": [5],
  "10": [3],
  "11": [3],
  "12": [3, 4],
  "13": [2],
  "14": [2],
  "15": [2],
  "16": [5],
  "17": [2],
  "18": [2],
  "19": [2],
  "20": [5],
  "21": [2],
  "22": [2],
  "23": [2],
  "24": [5],
  "26": [3],
  "27": [4],
  "28": [2],
  "29": [3],
  "30": [2],
  "31": [2],
  "32": [1],
  "33": [0],
  "34": [1],
  "35": [0],
  "36": [0],
  "37": [3],
  "38": [0],
  "39": [1],
  "40": [0],
  "41": [0],
  "42": [0],
  "43": [0],
  "44": [3],
  "45": [3],
} as const,
  featureValidBiomeTypeIndices: {
  "0": [5],
  "1": [3],
  "2": [4],
  "3": [4],
  "4": [4],
  "5": [4],
  "6": [1],
  "7": [1],
  "8": [1],
  "9": [1],
  "10": [5],
  "11": [5],
  "12": [5],
  "13": [2],
  "14": [2],
  "15": [2],
  "16": [2],
  "17": [3],
  "18": [3],
  "19": [3],
  "20": [3],
  "21": [0],
  "22": [0],
  "23": [0],
  "24": [0],
  "26": [5],
  "27": [5],
  "28": [2],
  "29": [5],
  "30": [1],
  "31": [4],
  "32": [0, 1],
  "33": [1],
  "34": [3],
  "35": [2],
  "36": [3],
  "37": [5],
  "38": [0],
  "39": [4],
  "40": [3],
  "41": [1],
  "42": [2],
  "43": [4],
  "44": [5],
  "45": [5],
} as const,
  featureTagsByFeatureType: {
  "0": ["ADJACENTTOCOAST", "NOTADJACENTTOLAND"],
  "1": ["ADJACENTTOSAMEBIOME", "NOTADJACENTTORIVER", "NOTNEARCOAST"],
  "11": ["NOTADJACENTTOICE"],
  "25": ["VOLCANO"],
  "26": ["IN_LAKE"],
  "28": ["ADJACENTMOUNTAIN", "NOTNEARCOAST"],
  "29": ["ADJACENTTOLAND", "FEATURE_REEF", "NOTADJACENTTOICE", "SHALLOWWATER"],
  "30": ["FEATURE_FOREST"],
  "31": ["NOTADJACENTTORIVER", "NOTNEARCOAST"],
  "32": ["WATERFALL"],
  "34": ["WATERFALL"],
  "35": ["VOLCANO"],
  "37": ["ADJACENTTOLAND", "NOTADJACENTTOICE", "SHALLOWWATER", "VOLCANO"],
  "39": ["ADJACENTTOSAMEBIOME", "NOTADJACENTMOUNTAIN"],
  "41": ["VOLCANO"],
  "44": ["ADJACENTTOSAMETERRAIN", "NOTADJACENTTOICE", "SHALLOWWATER"],
  "45": ["ADJACENTCLIFF", "ADJACENTTOLAND", "NOLANDOPPOSITECLIFF", "NOTADJACENTTOICE", "SHALLOWWATER"],
} as const,
  featurePolicies: {
  "0": { noLake: true, placementClass: "THREETRIANGLEDEEPOCEAN", naturalWonderTiles: 3, naturalWonderDirection: -1 },
  "1": { noLake: true, placementClass: "FOURPARALLELAGRM", naturalWonderTiles: 4, naturalWonderDirection: -1 },
  "2": { noLake: false, placementClass: "SCATTER" },
  "3": { noLake: false, placementClass: "ISOLATED" },
  "4": { noLake: false, placementClass: "RIVERMOUTH" },
  "5": { noLake: false, placementClass: "RIVERMOUTH" },
  "6": { noLake: false, placementClass: "SCATTER" },
  "7": { noLake: false, placementClass: "NEARRIVER" },
  "8": { noLake: false, placementClass: "RIVERMOUTH" },
  "9": { noLake: false, placementClass: "RIVERMOUTH" },
  "10": { noLake: true, placementClass: "REEF" },
  "11": { noLake: true, placementClass: "REEF" },
  "12": { noLake: true, placementClass: "ICE" },
  "13": { noLake: false, placementClass: "SCATTER" },
  "14": { noLake: false, placementClass: "ISOLATED" },
  "15": { noLake: false, placementClass: "RIVERMOUTH" },
  "16": { noLake: false, placementClass: "RIVERMOUTH" },
  "17": { noLake: false, placementClass: "SCATTER" },
  "18": { noLake: false, placementClass: "COASTAL" },
  "19": { noLake: false, placementClass: "RIVERMOUTH" },
  "20": { noLake: false, placementClass: "RIVERMOUTH" },
  "21": { noLake: false, placementClass: "SCATTER" },
  "22": { noLake: false, placementClass: "NEARRIVER" },
  "23": { noLake: false, placementClass: "RIVERMOUTH" },
  "24": { noLake: false, placementClass: "RIVERMOUTH" },
  "25": { noLake: false, placementClass: "VOLCANO" },
  "26": { noLake: false, placementClass: "IN_LAKE" },
  "27": { noLake: false, placementClass: "OPEN_WATERS" },
  "28": { noLake: false, placementClass: "TWOADJACENT", naturalWonderTiles: 2, naturalWonderDirection: -1, naturalWonderPlaceFirst: true },
  "29": { noLake: true, placementClass: "FOURADJACENT", naturalWonderTiles: 4, naturalWonderDirection: -1 },
  "30": { noLake: false, placementClass: "THREETRIANGLE", naturalWonderTiles: 3, naturalWonderDirection: -1 },
  "31": { noLake: false, minimumElevation: 350, placementClass: "FOURPARALLELAGRM", naturalWonderTiles: 4, naturalWonderDirection: -1 },
  "32": { noLake: false, placementClass: "ONE", naturalWonderTiles: 1, naturalWonderDirection: -1, naturalWonderPlaceFirst: true },
  "33": { noLake: false, placementClass: "FOURL", naturalWonderTiles: 4, naturalWonderDirection: -1 },
  "34": { noLake: false, placementClass: "ONE", naturalWonderTiles: 1, naturalWonderDirection: -1, naturalWonderPlaceFirst: true },
  "35": { noLake: false, placementClass: "THREETRIANGLE", naturalWonderTiles: 3, naturalWonderDirection: -1 },
  "36": { noLake: false, placementClass: "TWOADJACENT", naturalWonderTiles: 2, naturalWonderDirection: -1 },
  "37": { noLake: true, placementClass: "FOURPARALLELAGRM", naturalWonderTiles: 4, naturalWonderDirection: -1 },
  "38": { noLake: false, placementClass: "THREETRIANGLE", naturalWonderTiles: 3, naturalWonderDirection: -1 },
  "39": { noLake: false, placementClass: "ONE", naturalWonderTiles: 1, naturalWonderDirection: -1 },
  "40": { noLake: false, placementClass: "THREETRIANGLE", naturalWonderTiles: 3, naturalWonderDirection: -1 },
  "41": { noLake: false, placementClass: "THREETRIANGLE", naturalWonderTiles: 3, naturalWonderDirection: 2 },
  "42": { noLake: false, placementClass: "THREETRIANGLE", naturalWonderTiles: 3, naturalWonderDirection: 1 },
  "43": { noLake: false, placementClass: "FOURPARALLELAGRM", naturalWonderTiles: 4, naturalWonderDirection: -1 },
  "44": { noLake: false, placementClass: "ONE", naturalWonderTiles: 1, naturalWonderDirection: -1 },
  "45": { noLake: true, placementClass: "TWO", naturalWonderTiles: 2, naturalWonderDirection: -1 },
} as const,
  resourceTypes: {
  "RESOURCE_CAMELS": 17,
  "RESOURCE_CITRUS": 35,
  "RESOURCE_CLAY": 42,
  "RESOURCE_CLOVES": 31,
  "RESOURCE_COAL": 36,
  "RESOURCE_COCOA": 24,
  "RESOURCE_COFFEE": 33,
  "RESOURCE_COTTON": 0,
  "RESOURCE_COWRIE": 52,
  "RESOURCE_CRABS": 51,
  "RESOURCE_DATES": 1,
  "RESOURCE_DYES": 2,
  "RESOURCE_FISH": 3,
  "RESOURCE_FLAX": 43,
  "RESOURCE_FURS": 25,
  "RESOURCE_GOLD": 4,
  "RESOURCE_GOLD_DISTANT_LANDS": 5,
  "RESOURCE_GYPSUM": 6,
  "RESOURCE_HARDWOOD": 49,
  "RESOURCE_HIDES": 18,
  "RESOURCE_HORSES": 19,
  "RESOURCE_INCENSE": 7,
  "RESOURCE_IRON": 20,
  "RESOURCE_IVORY": 8,
  "RESOURCE_JADE": 9,
  "RESOURCE_KAOLIN": 10,
  "RESOURCE_LAPIS_LAZULI": 23,
  "RESOURCE_LIMESTONE": 46,
  "RESOURCE_LLAMAS": 48,
  "RESOURCE_MANGOS": 41,
  "RESOURCE_MARBLE": 11,
  "RESOURCE_NICKEL": 37,
  "RESOURCE_NITER": 30,
  "RESOURCE_OIL": 38,
  "RESOURCE_PEARLS": 12,
  "RESOURCE_PITCH": 54,
  "RESOURCE_QUININE": 39,
  "RESOURCE_RICE": 45,
  "RESOURCE_RUBBER": 40,
  "RESOURCE_RUBIES": 44,
  "RESOURCE_SALT": 21,
  "RESOURCE_SILK": 13,
  "RESOURCE_SILVER": 14,
  "RESOURCE_SILVER_DISTANT_LANDS": 15,
  "RESOURCE_SPICES": 26,
  "RESOURCE_SUGAR": 27,
  "RESOURCE_TEA": 28,
  "RESOURCE_TIN": 47,
  "RESOURCE_TOBACCO": 34,
  "RESOURCE_TRUFFLES": 29,
  "RESOURCE_TURTLES": 53,
  "RESOURCE_WHALES": 32,
  "RESOURCE_WILD_GAME": 50,
  "RESOURCE_WINE": 16,
  "RESOURCE_WOOL": 22,
} as const,
  resourceValidPlacementRows: {
  "0": [[1, 2, 8], [2, 2, 15], [4, 2, 4], [1, 2, -1]],
  "1": [[4, 2, -1], [4, 2, 3]],
  "2": [[5, 3, -1]],
  "3": [[5, 3, -1]],
  "4": [[1, 1, -1], [2, 1, -1], [3, 1, -1]],
  "6": [[0, 1, -1], [2, 2, -1], [2, 1, -1]],
  "7": [[2, 2, 13], [4, 2, 2]],
  "8": [[1, 2, 6], [2, 2, -1], [2, 1, -1], [2, 2, 14], [3, 2, -1], [3, 2, 17], [4, 2, -1], [4, 2, 2]],
  "9": [[0, 2, -1], [2, 2, -1], [3, 2, -1]],
  "10": [[1, 2, 7], [2, 2, 14], [3, 2, 18]],
  "11": [[1, 2, -1], [1, 1, -1], [2, 1, -1]],
  "12": [[5, 3, -1]],
  "13": [[1, 2, 8], [2, 2, 15], [3, 2, 19], [2, 2, -1]],
  "14": [[0, 1, -1], [4, 1, -1]],
  "16": [[1, 2, -1], [2, 2, -1]],
  "17": [[2, 2, -1], [2, 1, -1], [4, 2, -1], [4, 1, -1]],
  "18": [[0, 2, -1], [0, 2, 21], [0, 2, 22], [0, 2, 23], [1, 2, -1], [2, 2, -1]],
  "19": [[1, 2, -1], [2, 2, -1]],
  "20": [[0, 1, -1], [1, 1, -1], [2, 1, -1], [3, 1, -1], [4, 1, -1]],
  "21": [[0, 2, -1], [2, 2, -1], [4, 2, -1]],
  "22": [[0, 1, -1], [1, 1, -1], [2, 1, -1], [3, 1, -1], [4, 1, -1]],
  "24": [[3, 2, 17]],
  "25": [[0, 2, 21], [0, 2, 23], [2, 2, 13]],
  "26": [[1, 2, 6], [3, 2, 17]],
  "27": [[1, 2, 8], [2, 2, 15], [3, 2, 19], [3, 2, -1]],
  "28": [[2, 2, -1], [1, 2, -1], [1, 1, -1]],
  "29": [[1, 2, -1], [1, 1, -1], [0, 2, 22], [1, 2, 7], [2, 2, 14]],
  "30": [[0, 2, -1], [0, 2, 23], [1, 2, -1], [1, 2, 8], [2, 2, -1], [2, 2, 15], [3, 2, -1], [3, 2, 19], [4, 2, -1], [4, 2, 4]],
  "32": [[5, 3, -1]],
  "33": [[2, 1, -1], [3, 2, -1], [3, 1, -1], [3, 2, 17], [3, 2, 18], [3, 2, 19]],
  "34": [[1, 2, -1], [2, 2, -1], [1, 2, 6], [2, 2, 13]],
  "35": [[1, 2, -1], [2, 2, -1]],
  "36": [[0, 2, 21], [1, 1, -1], [1, 2, 6], [2, 1, -1], [2, 2, 13], [4, 2, -1]],
  "38": [[0, 2, -1], [0, 2, 21], [0, 2, 22], [0, 2, 23], [1, 2, 7], [4, 2, -1], [4, 2, 2], [4, 2, 3], [4, 2, 4]],
  "39": [[1, 2, 6], [2, 2, 13]],
  "40": [[1, 2, 6], [3, 2, 17]],
  "41": [[3, 2, -1], [3, 2, 17]],
  "42": [[0, 2, 22], [1, 2, 7], [2, 2, 14], [3, 2, 18], [4, 2, 3]],
  "43": [[1, 2, -1], [1, 1, -1], [1, 2, 6], [2, 2, -1], [2, 1, -1], [2, 2, 13]],
  "44": [[2, 1, -1], [3, 2, -1], [3, 1, -1], [4, 1, -1]],
  "45": [[1, 2, 7], [2, 2, 14], [3, 2, 18]],
  "46": [[1, 2, -1], [1, 1, -1], [2, 2, -1], [2, 1, -1], [4, 2, 3], [4, 1, -1]],
  "47": [[3, 2, -1], [3, 1, -1], [2, 2, -1], [2, 1, -1]],
  "48": [[3, 2, 17], [3, 2, -1], [3, 1, -1]],
  "49": [[0, 2, 22], [0, 2, -1], [0, 1, -1], [3, 2, 18], [3, 2, -1], [3, 1, -1]],
  "50": [[3, 2, 17], [3, 2, -1], [3, 1, -1], [0, 2, 22], [0, 2, -1], [0, 1, -1], [1, 2, 7], [1, 2, -1], [1, 1, -1]],
  "51": [[5, 3, -1], [1, 5, 9], [0, 5, 24], [3, 5, 20], [2, 5, 16], [4, 5, 5]],
  "52": [[5, 3, -1]],
  "53": [[5, 3, -1]],
  "54": [[0, 2, 21], [2, 2, 6], [1, 2, 13]],
} as const,
  resourcePlacementFlags: {
  "0": { adjacentToLand: false, lakeEligible: true },
  "1": { adjacentToLand: false, lakeEligible: true },
  "2": { adjacentToLand: true, lakeEligible: true },
  "3": { adjacentToLand: true, lakeEligible: true },
  "4": { adjacentToLand: false, lakeEligible: true },
  "5": { adjacentToLand: false, lakeEligible: true },
  "6": { adjacentToLand: false, lakeEligible: true },
  "7": { adjacentToLand: false, lakeEligible: true },
  "8": { adjacentToLand: false, lakeEligible: true },
  "9": { adjacentToLand: false, lakeEligible: true },
  "10": { adjacentToLand: false, lakeEligible: true },
  "11": { adjacentToLand: false, lakeEligible: true },
  "12": { adjacentToLand: true, lakeEligible: true },
  "13": { adjacentToLand: false, lakeEligible: true },
  "14": { adjacentToLand: false, lakeEligible: true },
  "15": { adjacentToLand: false, lakeEligible: true },
  "16": { adjacentToLand: false, lakeEligible: true },
  "17": { adjacentToLand: false, lakeEligible: true },
  "18": { adjacentToLand: false, lakeEligible: true },
  "19": { adjacentToLand: false, lakeEligible: true },
  "20": { adjacentToLand: false, lakeEligible: true },
  "21": { adjacentToLand: false, lakeEligible: true },
  "22": { adjacentToLand: false, lakeEligible: true },
  "23": { adjacentToLand: false, lakeEligible: true },
  "24": { adjacentToLand: false, lakeEligible: true },
  "25": { adjacentToLand: false, lakeEligible: true },
  "26": { adjacentToLand: false, lakeEligible: true },
  "27": { adjacentToLand: false, lakeEligible: true },
  "28": { adjacentToLand: false, lakeEligible: true },
  "29": { adjacentToLand: false, lakeEligible: true },
  "30": { adjacentToLand: false, lakeEligible: true },
  "31": { adjacentToLand: false, lakeEligible: true },
  "32": { adjacentToLand: true, lakeEligible: false },
  "33": { adjacentToLand: false, lakeEligible: true },
  "34": { adjacentToLand: false, lakeEligible: true },
  "35": { adjacentToLand: false, lakeEligible: true },
  "36": { adjacentToLand: false, lakeEligible: true },
  "37": { adjacentToLand: false, lakeEligible: true },
  "38": { adjacentToLand: false, lakeEligible: true },
  "39": { adjacentToLand: false, lakeEligible: true },
  "40": { adjacentToLand: false, lakeEligible: true },
  "41": { adjacentToLand: false, lakeEligible: true },
  "42": { adjacentToLand: false, lakeEligible: true },
  "43": { adjacentToLand: false, lakeEligible: true },
  "44": { adjacentToLand: false, lakeEligible: true },
  "45": { adjacentToLand: false, lakeEligible: true },
  "46": { adjacentToLand: false, lakeEligible: true },
  "47": { adjacentToLand: false, lakeEligible: true },
  "48": { adjacentToLand: false, lakeEligible: true },
  "49": { adjacentToLand: false, lakeEligible: true },
  "50": { adjacentToLand: false, lakeEligible: true },
  "51": { adjacentToLand: true, lakeEligible: true },
  "52": { adjacentToLand: true, lakeEligible: false },
  "53": { adjacentToLand: true, lakeEligible: false },
  "54": { adjacentToLand: false, lakeEligible: true },
} as const,
  riverTypes: {
  source: [
    "live-direct-control:2026-06-09:RiverTypes",
    "Base/modules/base-standard/data/unit-movement.xml",
    "Base/modules/base-standard/ui-next/tooltips/plot-tooltip/helpers.js",
  ],
  values: {
    NO_RIVER: -1,
    RIVER_MINOR: 0,
    RIVER_NAVIGABLE: 1,
  },
} as const,
} as const;

export type Civ7BrowserTablesV0 = typeof CIV7_BROWSER_TABLES_V0;

export type Civ7ResourceRowV1 = {
  readonly type: string;
  readonly classType: string;
  readonly weight: number;
  readonly minimumPerHemisphere: number;
  readonly hemisphereUnique: boolean;
  readonly staple: boolean;
  readonly tradeable: boolean;
  readonly unlocksCiv: boolean;
};

export type Civ7MapResourceMinimumAmountModifierRowV1 = {
  readonly mapType: string;
  readonly mapSizeType: string;
  readonly amount: number;
};

export type Civ7StartBiasValueRowV1 = {
  readonly civilizationType: string | null;
  readonly leaderType: string | null;
  readonly value: string;
  readonly score: number;
};

export type Civ7StartBiasScoreRowV1 = {
  readonly civilizationType: string | null;
  readonly leaderType: string | null;
  readonly score: number;
};

export type Civ7PolicyTablesV1 = {
  readonly version: 1;
  readonly source: readonly string[];
  /** Per-resource catalog row, keyed by GameInfo resource index. */
  readonly resourceRows: Readonly<Record<string, Civ7ResourceRowV1>>;
  /** Ages each resource is valid in (Resource_ValidAges), keyed by resource index. */
  readonly resourceValidAges: Readonly<Record<string, readonly string[]>>;
  /** Leaders requiring each resource (Resource_RequiredLeaders incl. DLC), keyed by resource index. */
  readonly resourceRequiredLeaders: Readonly<Record<string, readonly string[]>>;
  /**
   * Static approximation of ResourceBuilder.isResourceRequiredForAge: ages
   * for which the resource is leader-required AND age-valid. The live engine
   * additionally filters to leaders present in the running game.
   */
  readonly isResourceRequiredForAge: Readonly<Record<string, readonly string[]>>;
  /** GameInfo.MapResourceMinimumAmountModifier rows (maps.xml). */
  readonly mapResourceMinimumAmountModifier: readonly Civ7MapResourceMinimumAmountModifierRowV1[];
  /** GameInfo.StartBias* rows across base + DLC civilization/leader data. */
  readonly startBias: {
    readonly biomes: readonly Civ7StartBiasValueRowV1[];
    readonly terrains: readonly Civ7StartBiasValueRowV1[];
    readonly featureClasses: readonly Civ7StartBiasValueRowV1[];
    readonly resources: readonly Civ7StartBiasValueRowV1[];
    readonly rivers: readonly Civ7StartBiasScoreRowV1[];
    readonly lakes: readonly Civ7StartBiasScoreRowV1[];
    readonly adjacentToCoasts: readonly Civ7StartBiasScoreRowV1[];
    readonly naturalWonders: readonly Civ7StartBiasScoreRowV1[];
  };
  /** Start-placement globals from map-globals.js. */
  readonly startGlobals: {
    readonly requiredBufferBetweenMajorStarts: number;
    readonly desiredBufferBetweenMajorStarts: number;
    readonly requiredDistanceFromMajorForDiscoveries: number;
    readonly avoidSeamOffset: number;
    readonly ignoreStartSectorPctFromCtr: number;
    readonly startSectorWeight: number;
  };
};

export const CIV7_POLICY_TABLES_V1: Civ7PolicyTablesV1 = {
  "version": 1,
  "source": [
    "Base/modules/base-standard/data/resources.xml",
    "Base/modules/base-standard/data/resources-v2.xml",
    "DLC/ashoka-himiko-alt/modules/data/resources.xml",
    "Base/modules/base-standard/data/maps.xml",
    "Base/modules/base-standard/maps/map-globals.js",
    "Base/modules/age-antiquity/data/civilizations.xml",
    "Base/modules/age-exploration/data/civilizations.xml",
    "Base/modules/age-modern/data/civilizations.xml",
    "Base/modules/base-standard/data/leaders.xml",
    "DLC/assyria/modules/data/civilizations-antiquity.xml",
    "DLC/bulgaria/modules/data/civilizations-exploration.xml",
    "DLC/carthage/modules/data/civilizations-antiquity.xml",
    "DLC/dai-viet/modules/data/civilizations-exploration.xml",
    "DLC/edward-teach/modules/data/leaders.xml",
    "DLC/friedrich-xerxes-alt/modules/data/leaders.xml",
    "DLC/iceland/modules/data/civilizations-exploration.xml",
    "DLC/nepal/modules/data/civilizations-modern.xml",
    "DLC/pirate-republic/modules/data/civilizations-exploration.xml",
    "DLC/qajar/modules/data/civilizations-modern.xml",
    "DLC/sayyida-al-hurra/modules/data/leaders.xml",
    "DLC/shawnee-tecumseh/modules/data/civilizations-exploration.xml",
    "DLC/silla/modules/data/civilizations-antiquity.xml",
    "DLC/tonga/modules/data/civilizations-antiquity.xml"
  ],
  "resourceRows": {
    "0": {
      "type": "RESOURCE_COTTON",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": false
    },
    "1": {
      "type": "RESOURCE_DATES",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "2": {
      "type": "RESOURCE_DYES",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "3": {
      "type": "RESOURCE_FISH",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "4": {
      "type": "RESOURCE_GOLD",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 20,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": false
    },
    "5": {
      "type": "RESOURCE_GOLD_DISTANT_LANDS",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 25,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "6": {
      "type": "RESOURCE_GYPSUM",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "7": {
      "type": "RESOURCE_INCENSE",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "8": {
      "type": "RESOURCE_IVORY",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "9": {
      "type": "RESOURCE_JADE",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "10": {
      "type": "RESOURCE_KAOLIN",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": false
    },
    "11": {
      "type": "RESOURCE_MARBLE",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "12": {
      "type": "RESOURCE_PEARLS",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "13": {
      "type": "RESOURCE_SILK",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "14": {
      "type": "RESOURCE_SILVER",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 20,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": false
    },
    "15": {
      "type": "RESOURCE_SILVER_DISTANT_LANDS",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 25,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "16": {
      "type": "RESOURCE_WINE",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "17": {
      "type": "RESOURCE_CAMELS",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "18": {
      "type": "RESOURCE_HIDES",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 40,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "19": {
      "type": "RESOURCE_HORSES",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": true
    },
    "20": {
      "type": "RESOURCE_IRON",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": true
    },
    "21": {
      "type": "RESOURCE_SALT",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "22": {
      "type": "RESOURCE_WOOL",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "23": {
      "type": "RESOURCE_LAPIS_LAZULI",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": false,
      "unlocksCiv": false
    },
    "24": {
      "type": "RESOURCE_COCOA",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 5,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": true,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "25": {
      "type": "RESOURCE_FURS",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 5,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "26": {
      "type": "RESOURCE_SPICES",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 5,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": true,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "27": {
      "type": "RESOURCE_SUGAR",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 5,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": true,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "28": {
      "type": "RESOURCE_TEA",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 5,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": true,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "29": {
      "type": "RESOURCE_TRUFFLES",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "30": {
      "type": "RESOURCE_NITER",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": true
    },
    "31": {
      "type": "RESOURCE_CLOVES",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": false,
      "unlocksCiv": false
    },
    "32": {
      "type": "RESOURCE_WHALES",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "33": {
      "type": "RESOURCE_COFFEE",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "34": {
      "type": "RESOURCE_TOBACCO",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "35": {
      "type": "RESOURCE_CITRUS",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "36": {
      "type": "RESOURCE_COAL",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "37": {
      "type": "RESOURCE_NICKEL",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": false,
      "unlocksCiv": false
    },
    "38": {
      "type": "RESOURCE_OIL",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "39": {
      "type": "RESOURCE_QUININE",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 8,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "40": {
      "type": "RESOURCE_RUBBER",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "41": {
      "type": "RESOURCE_MANGOS",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "42": {
      "type": "RESOURCE_CLAY",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "43": {
      "type": "RESOURCE_FLAX",
      "classType": "RESOURCECLASS_CITY",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "44": {
      "type": "RESOURCE_RUBIES",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": false
    },
    "45": {
      "type": "RESOURCE_RICE",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "46": {
      "type": "RESOURCE_LIMESTONE",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "47": {
      "type": "RESOURCE_TIN",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 25,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": true,
      "tradeable": true,
      "unlocksCiv": false
    },
    "48": {
      "type": "RESOURCE_LLAMAS",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "49": {
      "type": "RESOURCE_HARDWOOD",
      "classType": "RESOURCECLASS_EMPIRE",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "50": {
      "type": "RESOURCE_WILD_GAME",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "51": {
      "type": "RESOURCE_CRABS",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "52": {
      "type": "RESOURCE_COWRIE",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "53": {
      "type": "RESOURCE_TURTLES",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    },
    "54": {
      "type": "RESOURCE_PITCH",
      "classType": "RESOURCECLASS_BONUS",
      "weight": 10,
      "minimumPerHemisphere": 0,
      "hemisphereUnique": false,
      "staple": false,
      "tradeable": true,
      "unlocksCiv": false
    }
  },
  "resourceValidAges": {
    "0": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "1": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "2": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "3": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "4": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "6": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "7": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "8": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "9": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "10": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "11": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "12": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "13": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "14": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "16": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "17": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "18": [
      "AGE_ANTIQUITY"
    ],
    "19": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "20": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "21": [
      "AGE_ANTIQUITY"
    ],
    "22": [
      "AGE_ANTIQUITY"
    ],
    "23": [
      "AGE_ANTIQUITY"
    ],
    "24": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "25": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "26": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "27": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "28": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "29": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "30": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "31": [
      "AGE_EXPLORATION"
    ],
    "32": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "33": [
      "AGE_MODERN"
    ],
    "34": [
      "AGE_MODERN"
    ],
    "35": [
      "AGE_MODERN"
    ],
    "36": [
      "AGE_MODERN"
    ],
    "37": [
      "AGE_MODERN"
    ],
    "38": [
      "AGE_MODERN"
    ],
    "39": [
      "AGE_MODERN"
    ],
    "40": [
      "AGE_MODERN"
    ],
    "41": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "42": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "43": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "44": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "45": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "46": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "47": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "48": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "49": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "50": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "51": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "52": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "53": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "54": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ]
  },
  "resourceRequiredLeaders": {
    "3": [
      "LEADER_HARRIET_TUBMAN"
    ],
    "4": [
      "LEADER_HATSHEPSUT"
    ],
    "7": [
      "LEADER_ASHOKA",
      "LEADER_ASHOKA_ALT"
    ],
    "9": [
      "LEADER_HIMIKO",
      "LEADER_HIMIKO_ALT"
    ],
    "11": [
      "LEADER_HATSHEPSUT"
    ],
    "19": [
      "LEADER_HATSHEPSUT"
    ],
    "24": [
      "LEADER_ASHOKA",
      "LEADER_ASHOKA_ALT",
      "LEADER_HATSHEPSUT",
      "LEADER_JOSE_RIZAL",
      "LEADER_MACHIAVELLI"
    ],
    "25": [
      "LEADER_HIMIKO",
      "LEADER_HIMIKO_ALT"
    ],
    "26": [
      "LEADER_ASHOKA",
      "LEADER_ASHOKA_ALT",
      "LEADER_HATSHEPSUT",
      "LEADER_JOSE_RIZAL",
      "LEADER_MACHIAVELLI"
    ],
    "27": [
      "LEADER_ASHOKA",
      "LEADER_ASHOKA_ALT",
      "LEADER_HATSHEPSUT",
      "LEADER_JOSE_RIZAL",
      "LEADER_MACHIAVELLI"
    ],
    "28": [
      "LEADER_ASHOKA",
      "LEADER_ASHOKA_ALT",
      "LEADER_HATSHEPSUT",
      "LEADER_JOSE_RIZAL",
      "LEADER_MACHIAVELLI"
    ]
  },
  "isResourceRequiredForAge": {
    "3": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "4": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "7": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "9": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION"
    ],
    "11": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "19": [
      "AGE_ANTIQUITY",
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "24": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "25": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "26": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "27": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ],
    "28": [
      "AGE_EXPLORATION",
      "AGE_MODERN"
    ]
  },
  "mapResourceMinimumAmountModifier": [
    {
      "mapType": "DEFAULT",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "DEFAULT",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "DEFAULT",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "DEFAULT",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_PANGAEA_PLUS_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_PANGAEA_PLUS_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_PANGAEA_PLUS_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_PANGAEA_PLUS_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_ARCHIPELAGO_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_ARCHIPELAGO_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_ARCHIPELAGO_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_ARCHIPELAGO_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_TERRA_INCOGNITA_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_TERRA_INCOGNITA_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_TERRA_INCOGNITA_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_TERRA_INCOGNITA_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_SHUFFLE_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_SHUFFLE_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_SHUFFLE_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_SHUFFLE_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_FRACTAL_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_FRACTAL_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_FRACTAL_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_FRACTAL_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_PLUS_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_PLUS_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_PLUS_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_PLUS_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_CONTINENTS_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    },
    {
      "mapType": "LOC_MAP_PANGAEA_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_TINY",
      "amount": -4
    },
    {
      "mapType": "LOC_MAP_PANGAEA_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_SMALL",
      "amount": -2
    },
    {
      "mapType": "LOC_MAP_PANGAEA_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_LARGE",
      "amount": 0
    },
    {
      "mapType": "LOC_MAP_PANGAEA_VORONOI_NAME",
      "mapSizeType": "MAPSIZE_HUGE",
      "amount": 4
    }
  ],
  "startBias": {
    "biomes": [
      {
        "civilizationType": "CIVILIZATION_EGYPT",
        "leaderType": null,
        "value": "BIOME_DESERT",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_GREECE",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_HAN",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_KHMER",
        "leaderType": null,
        "value": "BIOME_TROPICAL",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MAYA",
        "leaderType": null,
        "value": "BIOME_TROPICAL",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_PERSIA",
        "leaderType": null,
        "value": "BIOME_DESERT",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_ROME",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_CHOLA",
        "leaderType": null,
        "value": "BIOME_TROPICAL",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_HAWAII",
        "leaderType": null,
        "value": "BIOME_MARINE",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_INCA",
        "leaderType": null,
        "value": "BIOME_PLAINS",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_INCA",
        "leaderType": null,
        "value": "BIOME_DESERT",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_SONGHAI",
        "leaderType": null,
        "value": "BIOME_PLAINS",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_SONGHAI",
        "leaderType": null,
        "value": "BIOME_DESERT",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_BUGANDA",
        "leaderType": null,
        "value": "BIOME_TROPICAL",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MEIJI",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MEXICO",
        "leaderType": null,
        "value": "BIOME_PLAINS",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MEXICO",
        "leaderType": null,
        "value": "BIOME_DESERT",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_QING",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_RUSSIA",
        "leaderType": null,
        "value": "BIOME_TUNDRA",
        "score": 15
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_AMINA",
        "value": "BIOME_PLAINS",
        "score": 20
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_AMINA",
        "value": "BIOME_DESERT",
        "score": 20
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_CATHERINE",
        "value": "BIOME_TUNDRA",
        "score": 10
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_CONFUCIUS",
        "value": "BIOME_GRASSLAND",
        "score": 10
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_HATSHEPSUT",
        "value": "BIOME_DESERT",
        "score": 10
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_JOSE_RIZAL",
        "value": "BIOME_TROPICAL",
        "score": 10
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_TRUNG_TRAC",
        "value": "BIOME_TROPICAL",
        "score": 10
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_XERXES",
        "value": "BIOME_DESERT",
        "score": 10
      },
      {
        "civilizationType": "CIVILIZATION_CARTHAGE",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_DAI_VIET",
        "leaderType": null,
        "value": "BIOME_TROPICAL",
        "score": 5
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_XERXES_ALT",
        "value": "BIOME_DESERT",
        "score": 10
      },
      {
        "civilizationType": "CIVILIZATION_ICELAND",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_ICELAND",
        "leaderType": null,
        "value": "BIOME_TUNDRA",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_QAJAR",
        "leaderType": null,
        "value": "BIOME_PLAINS",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_QAJAR",
        "leaderType": null,
        "value": "BIOME_DESERT",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_SILLA",
        "leaderType": null,
        "value": "BIOME_GRASSLAND",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_TONGA",
        "leaderType": null,
        "value": "BIOME_TROPICAL",
        "score": 5
      }
    ],
    "terrains": [
      {
        "civilizationType": "CIVILIZATION_AKSUM",
        "leaderType": null,
        "value": "TERRAIN_HILL",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_EGYPT",
        "leaderType": null,
        "value": "TERRAIN_NAVIGABLE_RIVER",
        "score": 20
      },
      {
        "civilizationType": "CIVILIZATION_GREECE",
        "leaderType": null,
        "value": "TERRAIN_HILL",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_MISSISSIPPIAN",
        "leaderType": null,
        "value": "TERRAIN_FLAT",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_INCA",
        "leaderType": null,
        "value": "TERRAIN_MOUNTAIN",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_SONGHAI",
        "leaderType": null,
        "value": "TERRAIN_NAVIGABLE_RIVER",
        "score": 20
      },
      {
        "civilizationType": "CIVILIZATION_AMERICA",
        "leaderType": null,
        "value": "TERRAIN_HILL",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_MUGHAL",
        "leaderType": null,
        "value": "TERRAIN_FLAT",
        "score": 15
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_HATSHEPSUT",
        "value": "TERRAIN_NAVIGABLE_RIVER",
        "score": 20
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_IBN_BATTUTA",
        "value": "TERRAIN_FLAT",
        "score": 10
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_PACHACUTI",
        "value": "TERRAIN_MOUNTAIN",
        "score": 40
      },
      {
        "civilizationType": "CIVILIZATION_ASSYRIA",
        "leaderType": null,
        "value": "TERRAIN_FLAT",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_BULGARIA",
        "leaderType": null,
        "value": "TERRAIN_HILL",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_NEPAL",
        "leaderType": null,
        "value": "TERRAIN_MOUNTAIN",
        "score": 20
      },
      {
        "civilizationType": "CIVILIZATION_SHAWNEE",
        "leaderType": null,
        "value": "TERRAIN_NAVIGABLE_RIVER",
        "score": 20
      },
      {
        "civilizationType": "CIVILIZATION_SILLA",
        "leaderType": null,
        "value": "TERRAIN_HILL",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_TONGA",
        "leaderType": null,
        "value": "TERRAIN_COAST",
        "score": 15
      }
    ],
    "featureClasses": [
      {
        "civilizationType": "CIVILIZATION_KHMER",
        "leaderType": null,
        "value": "FEATURE_CLASS_FLOODPLAIN",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_MAURYA",
        "leaderType": null,
        "value": "FEATURE_CLASS_VEGETATED",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MAYA",
        "leaderType": null,
        "value": "FEATURE_CLASS_VEGETATED",
        "score": 15
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_HARRIET_TUBMAN",
        "value": "FEATURE_CLASS_VEGETATED",
        "score": 20
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_TRUNG_TRAC",
        "value": "FEATURE_CLASS_VEGETATED",
        "score": 20
      },
      {
        "civilizationType": "CIVILIZATION_DAI_VIET",
        "leaderType": null,
        "value": "FEATURE_CLASS_FLOODPLAIN",
        "score": 15
      }
    ],
    "resources": [
      {
        "civilizationType": "CIVILIZATION_ABBASID",
        "leaderType": null,
        "value": "RESOURCE_CAMELS",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MAJAPAHIT",
        "leaderType": null,
        "value": "RESOURCE_SPICES",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MING",
        "leaderType": null,
        "value": "RESOURCE_SILK",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_MONGOLIA",
        "leaderType": null,
        "value": "RESOURCE_HORSES",
        "score": 15
      },
      {
        "civilizationType": "CIVILIZATION_NORMAN",
        "leaderType": null,
        "value": "RESOURCE_IRON",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_FRENCH_EMPIRE",
        "leaderType": null,
        "value": "RESOURCE_WINE",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_PRUSSIA",
        "leaderType": null,
        "value": "RESOURCE_NITER",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_RUSSIA",
        "leaderType": null,
        "value": "RESOURCE_FURS",
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_SIAM",
        "leaderType": null,
        "value": "RESOURCE_IVORY",
        "score": 5
      }
    ],
    "rivers": [
      {
        "civilizationType": "CIVILIZATION_MISSISSIPPIAN",
        "leaderType": null,
        "score": 5
      },
      {
        "civilizationType": "CIVILIZATION_AMERICA",
        "leaderType": null,
        "score": 5
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_CHARLEMAGNE",
        "score": 10
      },
      {
        "civilizationType": "CIVILIZATION_ASSYRIA",
        "leaderType": null,
        "score": 5
      }
    ],
    "lakes": [
      {
        "civilizationType": "CIVILIZATION_BUGANDA",
        "leaderType": null,
        "score": 15
      }
    ],
    "adjacentToCoasts": [
      {
        "civilizationType": "CIVILIZATION_AKSUM",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": "CIVILIZATION_ABBASID",
        "leaderType": null,
        "score": 25
      },
      {
        "civilizationType": "CIVILIZATION_CHOLA",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": "CIVILIZATION_HAWAII",
        "leaderType": null,
        "score": 25
      },
      {
        "civilizationType": "CIVILIZATION_INCA",
        "leaderType": null,
        "score": 25
      },
      {
        "civilizationType": "CIVILIZATION_MAJAPAHIT",
        "leaderType": null,
        "score": 25
      },
      {
        "civilizationType": "CIVILIZATION_MING",
        "leaderType": null,
        "score": 25
      },
      {
        "civilizationType": "CIVILIZATION_NORMAN",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": "CIVILIZATION_SONGHAI",
        "leaderType": null,
        "score": 25
      },
      {
        "civilizationType": "CIVILIZATION_SPAIN",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": "CIVILIZATION_MEIJI",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_ISABELLA",
        "score": 200
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_LAFAYETTE",
        "score": 200
      },
      {
        "civilizationType": "CIVILIZATION_CARTHAGE",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_EDWARD_TEACH",
        "score": 200
      },
      {
        "civilizationType": "CIVILIZATION_ICELAND",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": "CIVILIZATION_PIRATE_REPUBLIC",
        "leaderType": null,
        "score": 150
      },
      {
        "civilizationType": null,
        "leaderType": "LEADER_SAYYIDA_AL_HURRA",
        "score": 200
      }
    ],
    "naturalWonders": [
      {
        "civilizationType": null,
        "leaderType": "LEADER_ISABELLA",
        "score": 1000
      }
    ]
  },
  "startGlobals": {
    "requiredBufferBetweenMajorStarts": 6,
    "desiredBufferBetweenMajorStarts": 12,
    "requiredDistanceFromMajorForDiscoveries": 3,
    "avoidSeamOffset": 2,
    "ignoreStartSectorPctFromCtr": 93,
    "startSectorWeight": 0.5
  }
};
