import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { compile } from "json-schema-to-typescript";

type JsonObject = Record<string, unknown>;

function assertPlainObject(value: unknown, label: string): asserts value is JsonObject {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label} must be a JSON object`);
  }
}

function stableJson(value: unknown): JsonObject {
  const text = JSON.stringify(value);
  if (!text) throw new Error("schema is not JSON-serializable");
  const parsed = JSON.parse(text) as unknown;
  assertPlainObject(parsed, "schema");
  return parsed;
}

async function writeArtifactsModule(args: {
  pkgRoot: string;
  outBase: string; // e.g. "standard-artifacts"
  schemaJson: JsonObject;
  typeName: string; // e.g. "StandardRecipeConfig"
  configTypes: string; // output from json-schema-to-typescript (trimmed)
  configConstName: string; // e.g. "STANDARD_RECIPE_CONFIG"
  schemaConstName: string; // e.g. "STANDARD_RECIPE_CONFIG_SCHEMA"
  configValue: unknown;
}): Promise<void> {
  const { pkgRoot, outBase, schemaJson, typeName, configTypes, configConstName, schemaConstName, configValue } = args;

  const jsLines = [
    `// This file is generated by scripts/generate-studio-recipe-types.ts`,
    `// Do not edit by hand; re-run \`bun run build:studio-recipes\`.`,
    ``,
    `export const ${configConstName} = ${JSON.stringify(configValue, null, 2)};`,
    `export const ${schemaConstName} = ${JSON.stringify(schemaJson, null, 2)};`,
    ``,
  ];

  const dtsLines = [
    `// This file is generated by scripts/generate-studio-recipe-types.ts`,
    `// Do not edit by hand; re-run \`bun run build:studio-recipes\`.`,
    ``,
    `import type { TSchema } from "typebox";`,
    ``,
    configTypes.trimEnd(),
    ``,
    `export const ${configConstName}: Readonly<${typeName}>;`,
    `export const ${schemaConstName}: TSchema;`,
    ``,
  ];

  // Note: we intentionally embed JSON here so the UI can import schema/defaults
  // without importing the runtime recipe module (which is worker-only).
  await writeFile(resolve(pkgRoot, "dist", "recipes", `${outBase}.js`), jsLines.join("\n"));
  await writeFile(resolve(pkgRoot, "dist", "recipes", `${outBase}.d.ts`), dtsLines.join("\n"));
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const pkgRoot = resolve(__dirname, "..");

const distBrowserTest = resolve(pkgRoot, "dist", "recipes", "browser-test.js");
const distStandard = resolve(pkgRoot, "dist", "recipes", "standard.js");

const mod = (await import(pathToFileURL(distBrowserTest).href)) as unknown as {
  BROWSER_TEST_FOUNDATION_STAGE_CONFIG: unknown;
  BROWSER_TEST_RECIPE_CONFIG: unknown;
  BROWSER_TEST_RECIPE_CONFIG_SCHEMA: unknown;
};

const schemaJson = stableJson(mod.BROWSER_TEST_RECIPE_CONFIG_SCHEMA);

await writeFile(
  resolve(pkgRoot, "dist", "recipes", "browser-test.schema.json"),
  JSON.stringify(schemaJson, null, 2)
);

const configTypes = await compile(schemaJson, "BrowserTestRecipeConfig", {
  bannerComment: "",
  style: {
    singleQuote: false,
    semi: true,
  },
});

const recipeTypeExports = [
  `export type BrowserTestFoundationStageConfig = NonNullable<BrowserTestRecipeConfig["foundation"]>;`,
  `export type BrowserTestFoundationStageKnobsConfig = NonNullable<BrowserTestFoundationStageConfig["knobs"]>;`,
  `export type BrowserTestFoundationStageAdvancedConfig = NonNullable<BrowserTestFoundationStageConfig["advanced"]>;`,
  `export type BrowserTestRecipeCompiledConfig = Readonly<{`,
  `  foundation?: BrowserTestFoundationStageAdvancedConfig;`,
  `}>;`,
  ``,
];

const browserTestDts = [
  `import type { ExtendedMapContext } from "@swooper/mapgen-core";`,
  `import type { RecipeModule } from "@swooper/mapgen-core/authoring";`,
  `import type { TSchema } from "typebox";`,
  ``,
  configTypes.trimEnd(),
  ``,
  ...recipeTypeExports,
  `export const BROWSER_TEST_FOUNDATION_STAGE_CONFIG: Readonly<BrowserTestFoundationStageConfig>;`,
  `export const BROWSER_TEST_RECIPE_CONFIG: Readonly<BrowserTestRecipeConfig>;`,
  `export const BROWSER_TEST_RECIPE_CONFIG_SCHEMA: TSchema;`,
  `export const compileOpsById: Readonly<Record<string, unknown>>;`,
  ``,
  `declare const recipe: RecipeModule<ExtendedMapContext, Readonly<BrowserTestRecipeConfig>, unknown>;`,
  `export default recipe;`,
  ``,
].join("\n");

await writeFile(resolve(pkgRoot, "dist", "recipes", "browser-test.d.ts"), browserTestDts);

await writeArtifactsModule({
  pkgRoot,
  outBase: "browser-test-artifacts",
  schemaJson,
  typeName: "BrowserTestRecipeConfig",
  configTypes,
  configConstName: "BROWSER_TEST_RECIPE_CONFIG",
  schemaConstName: "BROWSER_TEST_RECIPE_CONFIG_SCHEMA",
  configValue: mod.BROWSER_TEST_RECIPE_CONFIG ?? {},
});

const standardMod = (await import(pathToFileURL(distStandard).href)) as Record<string, unknown>;
const standardSchemaRaw = standardMod.STANDARD_RECIPE_CONFIG_SCHEMA;

let standardDts = "";

if (standardSchemaRaw) {
  const standardSchemaJson = stableJson(standardSchemaRaw);
  await writeFile(
    resolve(pkgRoot, "dist", "recipes", "standard.schema.json"),
    JSON.stringify(standardSchemaJson, null, 2)
  );

  const standardConfigTypes = await compile(standardSchemaJson, "StandardRecipeConfig", {
    bannerComment: "",
    style: {
      singleQuote: false,
      semi: true,
    },
  });

    standardDts = [
      `import type { ExtendedMapContext } from "@swooper/mapgen-core";`,
      `import type { RecipeModule } from "@swooper/mapgen-core/authoring";`,
      `import type { TSchema } from "typebox";`,
      ``,
      standardConfigTypes.trimEnd(),
      ``,
      `export const STANDARD_RECIPE_CONFIG: Readonly<StandardRecipeConfig>;`,
      `export const STANDARD_RECIPE_CONFIG_SCHEMA: TSchema;`,
      `export const compileOpsById: Readonly<Record<string, unknown>>;`,
      ``,
      `declare const recipe: RecipeModule<ExtendedMapContext, Readonly<StandardRecipeConfig>, unknown>;`,
    `export default recipe;`,
    ``,
  ].join("\n");

  await writeArtifactsModule({
    pkgRoot,
    outBase: "standard-artifacts",
    schemaJson: standardSchemaJson,
    typeName: "StandardRecipeConfig",
    configTypes: standardConfigTypes,
    configConstName: "STANDARD_RECIPE_CONFIG",
    schemaConstName: "STANDARD_RECIPE_CONFIG_SCHEMA",
    configValue: standardMod.STANDARD_RECIPE_CONFIG ?? {},
  });
} else {
  standardDts = [
    `import type { ExtendedMapContext } from "@swooper/mapgen-core";`,
    `import type { RecipeModule } from "@swooper/mapgen-core/authoring";`,
    ``,
    `export type StandardRecipeConfig = Readonly<Record<string, unknown>>;`,
    `export const STANDARD_RECIPE_CONFIG: Readonly<StandardRecipeConfig>;`,
    `export const compileOpsById: Readonly<Record<string, unknown>>;`,
    ``,
    `declare const recipe: RecipeModule<ExtendedMapContext, Readonly<StandardRecipeConfig>, unknown>;`,
    `export default recipe;`,
    ``,
  ].join("\n");
}

await writeFile(resolve(pkgRoot, "dist", "recipes", "standard.d.ts"), standardDts);
