export const HYDROLOGY_MOUTH_UNRESOLVED = 0;
export const HYDROLOGY_MOUTH_OCEAN = 1;
export const HYDROLOGY_MOUTH_ACCEPTED_LAKE = 2;
export const HYDROLOGY_MOUTH_CLOSED_BASIN = 3;
export const HYDROLOGY_MOUTH_SPILL_PATH = 4;

export const HYDROLOGY_SLOPE_NONE = 0;
export const HYDROLOGY_SLOPE_FLAT = 1;
export const HYDROLOGY_SLOPE_LOW = 2;
export const HYDROLOGY_SLOPE_MODERATE = 3;
export const HYDROLOGY_SLOPE_STEEP = 4;
export const HYDROLOGY_SLOPE_MOUNTAIN_BLOCKED = 5;

export const HYDROLOGY_FLOW_DRY = 0;
export const HYDROLOGY_FLOW_EPHEMERAL = 1;
export const HYDROLOGY_FLOW_INTERMITTENT = 2;
export const HYDROLOGY_FLOW_PERENNIAL = 3;
