/** Compact portable fields used by the observational browser viewer; none are native readback. */
export type CoherenceViewData = Readonly<{
  width: number; height: number; seaLevel: number;
  elevation: number[]; land: number[]; wet: number[]; mountain: number[]; hill: number[]; volcano: number[];
  river: number[]; receiver: number[]; discharge: number[]; bodyId: number[]; waterSurface: number[];
  bodies: Array<{ id: number; outlet: number; receiver: number; surface: number; outflow: number; wetTiles: number }>;
}>;

type ViewerInput = Readonly<{
  seed: number; size: string;
  variants: ReadonlyArray<{ id: string; label: string; kind: string; data: CoherenceViewData }>;
  records: Array<Record<string, unknown>>;
}>;

/** Marine hydraulic height is sea level; lake surfaces and dry ground retain their own evidence. */
export function coherenceSurfaceHeight(data: Pick<CoherenceViewData, "land" | "wet" | "seaLevel" | "waterSurface" | "elevation">, cell: number): number {
  return data.land[cell] === 0 ? data.seaLevel : data.wet[cell] === 1 ? data.waterSurface[cell]! : data.elevation[cell]!;
}

/** Builds an offline, dependency-free canvas comparison with a shared scale and exact hex coordinates. */
export function renderCoherenceViewer(input: ViewerInput): string {
  const payload = JSON.stringify(input).replaceAll("<", "\\u003c");
  return `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Earthlike coherence comparison</title>
<style>
:root{color-scheme:light;font-family:"Avenir Next",Avenir,system-ui,sans-serif;color:#21302d;background:#f5f7f7;letter-spacing:0}*{box-sizing:border-box}body{margin:0}header{padding:20px 24px 14px;border-bottom:1px solid #ccd5d2;background:white}h1{font-size:24px;margin:0 0 5px;font-weight:650}h2{font-size:16px;margin:0}p{margin:0;color:#536560;font-size:13px}.toolbar{padding:12px 24px;display:flex;align-items:center;gap:18px;flex-wrap:wrap;border-bottom:1px solid #ccd5d2;background:#edf2f0}.toolbar label,.panel label{font-size:13px;display:inline-flex;align-items:center;gap:6px}fieldset{padding:0;border:0;display:flex;gap:12px;margin:0}legend{position:absolute;clip:rect(0,0,0,0)}select,button,input{font:inherit;letter-spacing:0}select{max-width:100%;min-height:34px;border:1px solid #abbcb5;background:#fff;border-radius:4px;padding:5px 7px}input[type=number]{width:64px;padding:5px;border:1px solid #abbcb5}button{border:1px solid #95aaa0;background:#fff;padding:6px 10px;border-radius:4px;cursor:pointer;font-size:13px}button:hover{background:#e0eae5}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #167a91;outline-offset:2px}main{padding:18px 24px}.maps{display:grid;grid-template-columns:1fr 1fr;gap:20px}.panel{min-width:0}.panelbar{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:8px}.panelbar label{min-width:0;flex:1}.panelbar select{width:100%}.kind{height:20px;font-size:12px;color:#626f69}.map{display:block;width:100%;aspect-ratio:1.85;background:#d2e7ed;border:1px solid #bdccc6;cursor:crosshair;touch-action:manipulation}.tile{font:12px ui-monospace,SFMono-Regular,monospace;white-space:pre-wrap;min-height:60px;padding:8px 0;line-height:1.5}.legend{display:flex;gap:15px;flex-wrap:wrap;margin:8px 0 18px;font-size:12px;color:#4f625c}.swatch{display:inline-block;width:10px;height:10px;margin-right:5px;vertical-align:middle}.matrix{overflow:auto;margin-top:12px;border-top:1px solid #bccbc4}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;font-size:12px}th,td{padding:9px 10px;text-align:right;white-space:nowrap;border-bottom:1px solid #dce4df}th:first-child,td:first-child{text-align:left}th{font-weight:600;background:#e9efeb}tbody tr:hover{background:#e7f0ee}.failure{color:#9b3434}footer{display:flex;gap:16px;padding:16px 0;font-size:13px}a{color:#156878}.empty{padding:40px 0;color:#9b3434}.detailnote{font-size:12px;color:#5e6e67;padding-top:6px}.selection{font-variant-numeric:tabular-nums}@media(max-width:900px){header,.toolbar{padding-left:14px;padding-right:14px}main{padding:14px}.maps{grid-template-columns:1fr}.toolbar{gap:12px}.panelbar{gap:6px}h1{font-size:21px}}
</style>
<header><h1>Earthlike Coherence</h1><p id="identity"></p></header>
<div class="toolbar"><fieldset><legend>Map view</legend><label><input type="radio" name="view" value="terrain" checked>Terrain</label><label><input type="radio" name="view" value="network">Network</label><label><input type="radio" name="view" value="discharge">Discharge</label></fieldset><label><input id="detail" type="checkbox">Detail</label><label>X <input id="x" type="number" min="0" value="87"></label><label>Y <input id="y" type="number" min="0" value="31"></label><label><input id="drainage" type="checkbox">All dry receivers</label><span id="scale" class="selection"></span></div>
<main><div id="maps" class="maps"></div><div class="legend"><span><i class="swatch" style="background:#bedfe8"></i>Marine</span><span><i class="swatch" style="background:#438eaf"></i>Physical wet body</span><span><i class="swatch" style="background:#287e99"></i>Minor source</span><span><i class="swatch" style="background:#b34445"></i>Major source</span><span><i class="swatch" style="background:#82438f"></i>Body outlet</span><span>Tile labels: hydraulic height</span></div><p class="detailnote">Portable model units. Arrows are physical receiver intent, not observed native edges. Wet internal connectivity is omitted.</p><div id="matrix" class="matrix"></div><footer><a href="comparison.json">All metrics and configurations</a></footer></main>
<script type="application/json" id="payload">${payload}</script>
<script>
"use strict";
const input=JSON.parse(document.getElementById("payload").textContent), variants=input.variants;
document.getElementById("identity").textContent=input.size+" | map/game seeds "+input.seed+" | Portable generated evidence, not Civ7 readback";
const maps=document.getElementById("maps"), panels=[];
const controls={x:document.getElementById("x"),y:document.getElementById("y"),detail:document.getElementById("detail"),drainage:document.getElementById("drainage")};
let maximumDischarge=1, minimumElevation=Infinity, maximumElevation=-Infinity;
for(const variant of variants){for(const value of variant.data.elevation){minimumElevation=Math.min(minimumElevation,value);maximumElevation=Math.max(maximumElevation,value)}for(const value of variant.data.discharge) maximumDischarge=Math.max(maximumDischarge,value);for(const body of variant.data.bodies) maximumDischarge=Math.max(maximumDischarge,body.outflow)}
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v)), format=v=>Number.isFinite(v)?new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v):"-";
const percent=(n,d)=>d?format(n/d*100)+"%":"-";
const surfaceHeight=${coherenceSurfaceHeight.toString()};
const color=(a,b,t)=>"rgb("+a.map((value,i)=>Math.round(value+(b[i]-value)*clamp(t,0,1))).join(",")+")";
const mode=()=>document.querySelector('input[name="view"]:checked').value;
function point(data,i){return {x:i%data.width+((Math.floor(i/data.width)&1)?0.5:0),y:(data.height-1-Math.floor(i/data.width))*Math.sqrt(3)/2}}
function geometry(data,canvas){const focused=controls.detail.checked,cx=Number(controls.x.value),cy=Number(controls.y.value),radius=7;
const x0=focused?Math.max(0,cx-radius):0,x1=focused?Math.min(data.width-1,cx+radius):data.width-1,y0=focused?Math.max(0,cy-radius):0,y1=focused?Math.min(data.height-1,cy+radius):data.height-1;
const top=(data.height-1-y1)*Math.sqrt(3)/2,bottom=(data.height-1-y0)*Math.sqrt(3)/2;
const spacing=Math.min((canvas.width-44)/(x1-x0+2),(canvas.height-44)/(bottom-top+1.6));
const padX=(canvas.width-(x1-x0+2)*spacing)/2,padY=(canvas.height-(bottom-top+1.6)*spacing)/2;
return {spacing,x0,x1,y0,y1,to:i=>{const p=point(data,i);return {x:padX+(p.x-x0+0.6)*spacing,y:padY+(p.y-top+0.6)*spacing}},from:(x,y)=>{const row=clamp(Math.round(data.height-1-((y-padY)/spacing-0.6+top)/(Math.sqrt(3)/2)),y0,y1);const col=clamp(Math.round((x-padX)/spacing+x0-0.6-((row&1)?0.5:0)),x0,x1);return col+row*data.width}}}
function hex(ctx,p,r,fill,stroke){ctx.beginPath();for(let i=0;i<6;i++){const a=(i*60+30)*Math.PI/180,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
function arrow(ctx,geo,data,source,receiver,stroke,width){if(receiver<0||receiver>=data.width*data.height||source===receiver)return;const a=geo.to(source),b=geo.to(receiver);function segment(start,end){const dx=end.x-start.x,dy=end.y-start.y;ctx.strokeStyle=stroke;ctx.fillStyle=stroke;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke();if(geo.spacing>=8){const angle=Math.atan2(dy,dx),size=Math.max(2.5,Math.min(geo.spacing*0.25,7));ctx.beginPath();ctx.moveTo(end.x,end.y);ctx.lineTo(end.x-size*Math.cos(angle-0.5),end.y-size*Math.sin(angle-0.5));ctx.lineTo(end.x-size*Math.cos(angle+0.5),end.y-size*Math.sin(angle+0.5));ctx.closePath();ctx.fill()}}if(Math.abs(b.x-a.x)>geo.spacing*2){const shift=Math.sign(a.x-b.x)*data.width*geo.spacing;segment(a,{x:b.x+shift,y:b.y});segment({x:a.x-shift,y:a.y},b)}else segment(a,b)}
function inspect(panel,i){const d=panel.variant.data,x=i%d.width,y=Math.floor(i/d.width),body=d.bodies.find(b=>b.id===d.bodyId[i]);panel.tile.textContent="("+x+", "+y+")  ground "+d.elevation[i]+"  surface "+surfaceHeight(d,i)+"  class "+d.river[i]+"  discharge "+format(d.discharge[i])+"\\n"+(body?"Body "+body.id+" | "+body.wetTiles+" wet tiles | outlet ("+body.outlet%d.width+", "+Math.floor(body.outlet/d.width)+") -> ("+body.receiver%d.width+", "+Math.floor(body.receiver/d.width)+") | outflow "+format(body.outflow):"Receiver "+d.receiver[i]+" | "+(d.land[i]?"Dry land":"Marine"));}
function draw(panel){const d=panel.variant.data,canvas=panel.canvas,ctx=canvas.getContext("2d"),geo=geometry(d,canvas);panel.geo=geo;const verification=input.records.find(record=>record.id===panel.variant.id)?.verification?.status??"unavailable",caption=canvas.previousElementSibling;caption.textContent=panel.variant.kind+" | verification "+verification;caption.classList.toggle("failure",verification!=="pass");ctx.fillStyle="#f6f8f7";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.beginPath();ctx.rect(12,12,canvas.width-24,canvas.height-24);ctx.clip();
for(let y=geo.y0;y<=geo.y1;y++)for(let x=geo.x0;x<=geo.x1;x++){const i=x+y*d.width,p=geo.to(i);let fill;if(!d.land[i])fill="#bedfe8";else if(d.wet[i])fill="#438eaf";else if(mode()==="discharge")fill=color([235,244,235],[21,109,92],Math.log1p(d.discharge[i])/Math.log1p(maximumDischarge));else fill=color([224,235,187],[95,111,100],(d.elevation[i]-minimumElevation)/Math.max(1,maximumElevation-minimumElevation));hex(ctx,p,geo.spacing/Math.sqrt(3)+0.25,fill,geo.spacing>25?"#ffffff40":null);
if(mode()==="terrain"&&!d.wet[i]&&d.land[i]){ctx.strokeStyle="#324239";ctx.fillStyle=d.volcano[i]?"#bd4f32":"#34483f";ctx.lineWidth=Math.max(1,geo.spacing*0.06);if(d.mountain[i]||d.volcano[i]){ctx.beginPath();ctx.moveTo(p.x,p.y-geo.spacing*.27);ctx.lineTo(p.x+geo.spacing*.22,p.y+geo.spacing*.18);ctx.lineTo(p.x-geo.spacing*.22,p.y+geo.spacing*.18);ctx.closePath();ctx.fill()}else if(d.hill[i]){ctx.beginPath();ctx.arc(p.x,p.y+geo.spacing*.1,geo.spacing*.22,Math.PI,0);ctx.stroke()}}
if(controls.detail.checked&&geo.spacing>25){ctx.font=Math.max(11,Math.floor(geo.spacing*.2))+"px system-ui";ctx.fillStyle=d.wet[i]?"#fff":"#17251e";ctx.fillText(String(surfaceHeight(d,i)),p.x-geo.spacing*.2,p.y+geo.spacing*.38)}}
if(mode()!=="terrain"||controls.drainage.checked){for(let y=geo.y0;y<=geo.y1;y++)for(let x=geo.x0;x<=geo.x1;x++){const i=x+y*d.width;if(!d.land[i]||d.wet[i]||(!d.river[i]&&!controls.drainage.checked))continue;const cls=d.river[i],stroke=cls===2?"#b34445":cls===1?"#287e99":"#536b6150",line=cls?Math.max(1,geo.spacing*(cls===2?.13:.07)):.6;arrow(ctx,geo,d,i,d.receiver[i],stroke,line)}for(const body of d.bodies){const x=body.outlet%d.width,y=Math.floor(body.outlet/d.width);if(x>=geo.x0&&x<=geo.x1&&y>=geo.y0&&y<=geo.y1)arrow(ctx,geo,d,body.outlet,body.receiver,"#82438f",Math.max(1.5,geo.spacing*.13))}}
const selected=Number(controls.x.value)+Number(controls.y.value)*d.width;if(selected>=0&&selected<d.elevation.length){const p=geo.to(selected);ctx.strokeStyle="#eeb844";ctx.lineWidth=3;ctx.strokeRect(p.x-geo.spacing*.5,p.y-geo.spacing*.5,geo.spacing,geo.spacing)}ctx.restore();ctx.fillStyle="#3a5146";ctx.font="13px system-ui";ctx.fillText("N",canvas.width-22,20);inspect(panel,selected)}
function drawAll(){for(const panel of panels)draw(panel);document.getElementById("scale").textContent=mode()==="discharge"?"Shared log scale: 0 - "+format(maximumDischarge):"Shared ground scale: "+minimumElevation+" - "+maximumElevation}
for(let index=0;index<Math.min(2,variants.length);index++){const panel=document.createElement("section");panel.className="panel";const bar=document.createElement("div");bar.className="panelbar";const label=document.createElement("label");label.append(index===0?"A":"B");const select=document.createElement("select");select.setAttribute("aria-label",index===0?"Comparison A":"Comparison B");for(const v of variants){const option=document.createElement("option");option.value=v.id;option.textContent=v.label;select.append(option)}select.value=variants[index].id;label.append(select);const save=document.createElement("button");save.textContent="Download PNG";bar.append(label,save);const kind=document.createElement("div");kind.className="kind";const canvas=document.createElement("canvas");canvas.width=1600;canvas.height=865;canvas.className="map";canvas.setAttribute("aria-label","Portable whole-map comparison "+(index===0?"A":"B"));const tile=document.createElement("div");tile.className="tile";panel.append(bar,kind,canvas,tile);maps.append(panel);const state={variant:variants[index],canvas,tile,geo:null};panels.push(state);kind.textContent=state.variant.kind;select.onchange=()=>{state.variant=variants.find(v=>v.id===select.value);kind.textContent=state.variant.kind;draw(state)};save.onclick=()=>canvas.toBlob(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=state.variant.id+"-"+mode()+(controls.detail.checked?"-detail":"")+".png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});canvas.onpointermove=event=>{const rect=canvas.getBoundingClientRect();inspect(state,state.geo.from((event.clientX-rect.left)*canvas.width/rect.width,(event.clientY-rect.top)*canvas.height/rect.height))};canvas.onclick=event=>{const rect=canvas.getBoundingClientRect(),i=state.geo.from((event.clientX-rect.left)*canvas.width/rect.width,(event.clientY-rect.top)*canvas.height/rect.height);controls.x.value=i%state.variant.data.width;controls.y.value=Math.floor(i/state.variant.data.width);drawAll()}}
if(variants.length){controls.x.max=variants[0].data.width-1;controls.y.max=variants[0].data.height-1;controls.x.value=clamp(87,0,Number(controls.x.max));controls.y.value=clamp(31,0,Number(controls.y.max));for(const el of [...Object.values(controls),...document.querySelectorAll('input[name="view"]')])el.addEventListener("change",()=>{controls.x.value=clamp(Number(controls.x.value)||0,0,Number(controls.x.max));controls.y.value=clamp(Number(controls.y.value)||0,0,Number(controls.y.max));drawAll()});drawAll()}else{maps.textContent="No variant completed. Failure records are retained in comparison.json.";maps.className="empty"}
const table=document.createElement("table"),thead=document.createElement("thead"),hr=document.createElement("tr");for(const title of ["Variant","Generation","Verification","River / exposed","Major / exposed","Wet / original","Bodies","Single-tile bodies","Body size p90","Equal-height dry edges","Major segment starts","Unwritten classified wet exits","Rough / exposed","Ground changes","Receiver changes","Wet changes","Class changes","Discharge changes","Surface changes","Mountain changes","Hill changes","Volcano changes"]){const th=document.createElement("th");th.textContent=title;hr.append(th)}thead.append(hr);table.append(thead);const tbody=document.createElement("tbody"),base=variants.find(v=>v.id==="baseline");
for(const record of input.records){const row=document.createElement("tr"),v=variants.find(v=>v.id===record.id),network=record.networkCoherence,rough=record.metrics?.relief?.plannedRoughTerrain,verification=record.verification?.status??"unavailable";const changed=key=>base&&v?v.data[key].reduce((n,value,i)=>n+Number(value!==base.data[key][i]),0):null;for(const value of [record.label,record.status,verification,network?percent(network.minorSources+network.majorSources,network.exposedLand):"-",network?percent(network.majorSources,network.exposedLand):"-",network?percent(network.originalLand-network.exposedLand,network.originalLand):"-",network?.bodyCount??"-",network?.singleTileBodyCount??"-",network?.bodySizes.p90??"-",network?.equalHeightDryReceivers??"-",network?.majorSegmentStarts.length??"-",network?.unauthoredClassifiedWetOutletCount??"-",rough?percent(rough.count,rough.population):"-",changed("elevation")??"-",changed("receiver")??"-",changed("wet")??"-",changed("river")??"-",changed("discharge")??"-",changed("waterSurface")??"-",changed("mountain")??"-",changed("hill")??"-",changed("volcano")??"-"]){const td=document.createElement("td");td.textContent=String(value);row.append(td)}if(record.status==="failed"||verification!=="pass"){row.className="failure";row.title=record.error?.message??record.verification?.reasons?.join("; ")??"Verification unavailable"}tbody.append(row)}table.append(tbody);document.getElementById("matrix").append(table);
</script></html>`;
}
