import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  applyGeneratedFilePlan,
  type GeneratedFilePlan,
} from "@civ7/plugin-files/generated-file-plan";
import {
  buildCanonicalMapConfigSchema,
  type ValidatedMapConfig,
} from "../src/maps/configs/canonical.js";
import { deriveStandardRecipeArtifacts } from "../src/recipes/standard/artifacts.js";
import { loadSwooperMapConfigCatalog } from "./catalog-source.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const pkgRoot = resolve(__dirname, "..");
function stableJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderMapConfigsArtifact(configs: readonly ValidatedMapConfig[]): string {
  const values = configs.map((config) => config.canonicalConfig);
  return `// This file is generated by scripts/generate-studio-map-catalog.ts
// Do not edit by hand; re-run \`nx run swooper-physics:gen:studio-map-catalog\`.

export const standardMapConfigs = ${JSON.stringify(values, null, 2)};
`;
}

function renderMapConfigsDts(): string {
  return `// This file is generated by scripts/generate-studio-map-catalog.ts
// Do not edit by hand; re-run \`nx run swooper-physics:gen:studio-map-catalog\`.

import type { MapConfigEnvelope } from "@civ7/studio-contract";

/** Canonical envelopes in durable shipped catalog order; transient Studio deploy configs are absent. */
export const standardMapConfigs: ReadonlyArray<MapConfigEnvelope>;
`;
}

function buildSwooperCatalogMetadataFilePlan(options: {
  configs: readonly ValidatedMapConfig[];
  envelopeSchema: unknown;
}): GeneratedFilePlan {
  return {
    exclusiveSets: [],
    files: [
      {
        relativePath: "dist/recipes/standard-map-config.schema.json",
        content: stableJson(options.envelopeSchema),
      },
      {
        relativePath: "dist/recipes/standard-map-configs.js",
        content: renderMapConfigsArtifact(options.configs),
      },
      {
        relativePath: "dist/recipes/standard-map-configs.d.ts",
        content: renderMapConfigsDts(),
      },
    ],
  };
}

/** Applies the admitted Studio catalog metadata plan below its selected package root. */
export async function generateSwooperStudioCatalogMetadata(
  options: Readonly<{
    catalogConfigIds?: unknown;
    outputRoot?: string;
  }> = {}
): Promise<{ configCount: number }> {
  const { schema: recipeSchema } = deriveStandardRecipeArtifacts();
  const configs = await loadSwooperMapConfigCatalog({
    catalogConfigIds: options.catalogConfigIds,
  });
  const envelopeSchema = buildCanonicalMapConfigSchema(recipeSchema);
  const plan = buildSwooperCatalogMetadataFilePlan({ configs, envelopeSchema });
  await applyGeneratedFilePlan(plan, { outputRoot: options.outputRoot ?? pkgRoot });
  return { configCount: configs.length };
}

async function main(): Promise<void> {
  const result = await generateSwooperStudioCatalogMetadata();
  console.log(
    `Generated ${result.configCount} Studio catalog map configs from catalog membership.`
  );
}

if (import.meta.main) {
  await main();
}
