/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: `bun scripts/mapgen-studio/generate-civ7-browser-tables.ts`
 * Source of truth: `@civ7/map-policy` generated Civ7 table contract.
 */

export { CIV7_BROWSER_TABLES_V0 } from "@civ7/map-policy";
export type { Civ7BrowserTablesV0 } from "@civ7/map-policy";
