/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: `bun scripts/mapgen-studio/generate-civ7-browser-tables.ts`
 * Source of truth: Civ7 official resource XML under `.civ7/outputs/resources`
 *
 * Purpose:
 * - Provide Civ7-derived terrain/biome/feature indices for mock generation.
 * - Keep browser Studio, diagnostics, and adapter mocks on the same GameInfo order.
 */

export const CIV7_BROWSER_TABLES_V0 = {
  version: 0 as const,
  source: [
  "Base/modules/base-standard/data/racetowonders-terrain.xml",
  "Base/modules/base-standard/data/marvelous-mountains-terrain.xml",
  "Base/modules/base-standard/data/terrain.xml",
  "DLC/mountain-natural-wonders/modules/data/terrain.xml",
  "DLC/water-wonders/modules/data/terrain.xml"
] as const,
  terrainTypeIndices: {
  "TERRAIN_COAST": 3,
  "TERRAIN_FLAT": 2,
  "TERRAIN_HILL": 1,
  "TERRAIN_MOUNTAIN": 0,
  "TERRAIN_NAVIGABLE_RIVER": 5,
  "TERRAIN_OCEAN": 4,
} as const,
  biomeGlobals: {
  "BIOME_DESERT": 4,
  "BIOME_GRASSLAND": 1,
  "BIOME_MARINE": 5,
  "BIOME_PLAINS": 2,
  "BIOME_TROPICAL": 3,
  "BIOME_TUNDRA": 0,
} as const,
  featureTypes: {
  "FEATURE_ATOLL": 27,
  "FEATURE_BARRIER_REEF": 29,
  "FEATURE_BERMUDA_TRIANGLE": 0,
  "FEATURE_COLD_REEF": 11,
  "FEATURE_DESERT_FLOODPLAIN_MINOR": 4,
  "FEATURE_DESERT_FLOODPLAIN_NAVIGABLE": 5,
  "FEATURE_FOREST": 6,
  "FEATURE_GRAND_CANYON": 31,
  "FEATURE_GRASSLAND_FLOODPLAIN_MINOR": 8,
  "FEATURE_GRASSLAND_FLOODPLAIN_NAVIGABLE": 9,
  "FEATURE_GREAT_BLUE_HOLE": 44,
  "FEATURE_GULLFOSS": 32,
  "FEATURE_HOERIKWAGGO": 33,
  "FEATURE_ICE": 12,
  "FEATURE_IGUAZU_FALLS": 34,
  "FEATURE_KILIMANJARO": 35,
  "FEATURE_LOTUS": 26,
  "FEATURE_MACHAPUCHARE": 40,
  "FEATURE_MANGROVE": 18,
  "FEATURE_MAPU_A_VAEA_BLOWHOLES": 45,
  "FEATURE_MARSH": 7,
  "FEATURE_MOUNT_EVEREST": 1,
  "FEATURE_MOUNT_FUJI": 41,
  "FEATURE_OASIS": 3,
  "FEATURE_PLAINS_FLOODPLAIN_MINOR": 15,
  "FEATURE_PLAINS_FLOODPLAIN_NAVIGABLE": 16,
  "FEATURE_RAINFOREST": 17,
  "FEATURE_REDWOOD_FOREST": 30,
  "FEATURE_REEF": 10,
  "FEATURE_SAGEBRUSH_STEPPE": 2,
  "FEATURE_SAVANNA_WOODLAND": 13,
  "FEATURE_TAIGA": 21,
  "FEATURE_THERA": 37,
  "FEATURE_TORRES_DEL_PAINE": 38,
  "FEATURE_TROPICAL_FLOODPLAIN_MINOR": 19,
  "FEATURE_TROPICAL_FLOODPLAIN_NAVIGABLE": 20,
  "FEATURE_TUNDRA_BOG": 22,
  "FEATURE_TUNDRA_FLOODPLAIN_MINOR": 23,
  "FEATURE_TUNDRA_FLOODPLAIN_NAVIGABLE": 24,
  "FEATURE_ULURU": 39,
  "FEATURE_VALLEY_OF_FLOWERS": 28,
  "FEATURE_VIHREN": 42,
  "FEATURE_VINICUNCA": 43,
  "FEATURE_VOLCANO": 25,
  "FEATURE_WATERING_HOLE": 14,
  "FEATURE_ZHANGJIAJIE": 36,
} as const,
} as const;

export type Civ7BrowserTablesV0 = typeof CIV7_BROWSER_TABLES_V0;
