const { writeJson } = require("@nx/devkit");
const path = require("node:path");

const PROJECT_KIND_CONTRACTS = {
  plugin: {
    tag: "kind:plugin",
    rootForName: (name) => `packages/plugins/${pluginSlugForName(name)}`,
    packageNameForName: (name) => `@civ7/${pluginSlugForName(name)}`,
  },
  foundation: {
    tag: "kind:foundation",
    rootForName: (name) => `packages/${name}`,
    packageNameForName: (name) => `@civ7/${name}`,
  },
  app: {
    tag: "kind:app",
    rootForName: (name) => `apps/${name}`,
    packageNameForName: (name) => name,
  },
};

const SUPPORTED_KINDS = new Set(Object.keys(PROJECT_KIND_CONTRACTS));
const PACKAGE_SCAN_IGNORED_DIRECTORIES = new Set([
  ".git",
  ".nx",
  "dist",
  "mod",
  "node_modules",
  "tmp",
]);

async function projectGenerator(tree, rawOptions) {
  const options = normalizeOptions(rawOptions);
  if (tree.exists(options.root) && tree.children(options.root).length > 0) {
    throw new Error(`Refusing to overwrite non-empty project root: ${options.root}`);
  }
  const packageNameCollision = findPackageNameCollision(tree, options.packageName, options.root);
  if (packageNameCollision) {
    throw new Error(
      `Refusing to generate ${options.packageName}; package name already exists at ${packageNameCollision}.`
    );
  }

  writeJson(tree, path.posix.join(options.root, "package.json"), packageJson(options));
  tree.write(path.posix.join(options.root, "tsconfig.json"), tsconfigJson(options));
  tree.write(path.posix.join(options.root, "src", "index.ts"), indexSource(options));
  tree.write(path.posix.join(options.root, "test", "index.test.ts"), testSource(options));
  tree.write(path.posix.join(options.root, "README.md"), readme(options));
}

function normalizeOptions(rawOptions) {
  const kind = String(rawOptions.kind ?? "").replace(/^kind:/, "");
  if (!SUPPORTED_KINDS.has(kind)) {
    throw new Error(
      `Habitat project generator supports only uniform kinds: plugin, foundation, app. Refusing "${rawOptions.kind}" because mod, engine, control, adapter, sdk, and tooling shapes are owned by their domain maintainers.`
    );
  }

  const name = slugify(rawOptions.name);
  const contract = PROJECT_KIND_CONTRACTS[kind];
  const expectedRoot = contract.rootForName(name);
  const expectedPackageName = contract.packageNameForName(name);
  const root = normalizePath(rawOptions.directory ?? expectedRoot);
  const packageName = rawOptions.packageName ?? expectedPackageName;

  if (root !== expectedRoot) {
    throw new Error(
      `Refusing mismatched Habitat project root for kind:${kind}: expected ${expectedRoot}, received ${root}.`
    );
  }

  if (packageName !== expectedPackageName) {
    throw new Error(
      `Refusing mismatched Habitat package name for kind:${kind}: expected ${expectedPackageName}, received ${packageName}.`
    );
  }

  return {
    kind,
    tag: contract.tag,
    name,
    root,
    packageName,
  };
}

function packageJson(options) {
  return {
    name: options.packageName,
    version: "0.1.0",
    private: true,
    nx: {
      tags: [options.tag],
    },
    type: "module",
    main: "./dist/index.js",
    types: "./dist/index.d.ts",
    files: ["dist"],
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
    },
    scripts: {
      build: "tsc -p tsconfig.json",
      check: "tsc -p tsconfig.json --noEmit",
      test: "bun test",
      clean: "rimraf dist",
    },
    engines: {
      node: "22.22.0",
    },
  };
}

function tsconfigJson(options) {
  return `{
  "extends": "${relativePrefix(options.root)}tsconfig.base.json",
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "noEmit": false
  },
  "include": ["src"]
}
`;
}

function indexSource(options) {
  return `export const habitatProjectKind = "${options.tag}" as const;\n\nexport function describeHabitatProject(): string {\n  return "${options.packageName} (${options.tag})";\n}\n`;
}

function testSource(options) {
  return `import { expect, test } from "bun:test";\nimport { habitatProjectKind } from "../src/index";\n\ntest("${options.packageName} declares its Habitat kind", () => {\n  expect(habitatProjectKind).toBe("${options.tag}");\n});\n`;
}

function readme(options) {
  return `# ${options.packageName}\n\nGenerated by \`@internal/habitat-harness:project\` for \`${options.tag}\`.\n\nKeep structure changes aligned with \`docs/projects/habitat-harness/taxonomy.md\`.\n`;
}

function slugify(value) {
  const slug = String(value ?? "")
    .trim()
    .replace(/^@[^/]+\//, "")
    .replace(/[^a-zA-Z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  if (!slug) throw new Error("Project name must contain at least one alphanumeric character.");
  return slug;
}

function pluginSlugForName(name) {
  return name.startsWith("plugin-") ? name : `plugin-${name}`;
}

function normalizePath(value) {
  return String(value).replace(/\\/g, "/").replace(/^\/+/, "").replace(/\/+$/g, "");
}

function findPackageNameCollision(tree, packageName, projectRoot) {
  for (const packageJsonPath of packageJsonPaths(tree)) {
    if (packageJsonPath === path.posix.join(projectRoot, "package.json")) continue;
    const parsed = readTreeJson(tree, packageJsonPath);
    if (parsed?.name === packageName) return packageJsonPath;
  }
  return null;
}

function packageJsonPaths(tree) {
  const paths = [];
  const roots = ["apps", "mods", "packages", "tools"];
  for (const root of roots) {
    collectPackageJsonPaths(tree, root, paths);
  }
  return paths;
}

function collectPackageJsonPaths(tree, directory, paths) {
  if (!tree.exists(directory)) return;
  if (tree.exists(path.posix.join(directory, "package.json"))) {
    paths.push(path.posix.join(directory, "package.json"));
  }
  for (const child of tree.children(directory)) {
    if (PACKAGE_SCAN_IGNORED_DIRECTORIES.has(child)) continue;
    const childPath = path.posix.join(directory, child);
    if (
      !tree.exists(path.posix.join(childPath, "package.json")) &&
      tree.children(childPath).length === 0
    ) {
      continue;
    }
    collectPackageJsonPaths(tree, childPath, paths);
  }
}

function readTreeJson(tree, filePath) {
  const contents = tree.read(filePath, "utf8");
  if (!contents) return null;
  return JSON.parse(contents);
}

function relativePrefix(root) {
  return `${root
    .split("/")
    .filter(Boolean)
    .map(() => "..")
    .join("/")}/`;
}

module.exports = {
  PROJECT_KIND_CONTRACTS,
  projectGenerator,
  default: projectGenerator,
};
