const { writeJson } = require("@nx/devkit");
const path = require("node:path");

const SUPPORTED_KINDS = new Set(["plugin", "foundation", "app"]);

async function projectGenerator(tree, rawOptions) {
  const options = normalizeOptions(rawOptions);
  if (tree.exists(options.root) && tree.children(options.root).length > 0) {
    throw new Error(`Refusing to overwrite non-empty project root: ${options.root}`);
  }

  writeJson(tree, path.posix.join(options.root, "package.json"), packageJson(options));
  tree.write(path.posix.join(options.root, "tsconfig.json"), tsconfigJson(options));
  tree.write(path.posix.join(options.root, "src", "index.ts"), indexSource(options));
  tree.write(path.posix.join(options.root, "test", "index.test.ts"), testSource(options));
  tree.write(path.posix.join(options.root, "README.md"), readme(options));
}

function normalizeOptions(rawOptions) {
  const kind = String(rawOptions.kind ?? "").replace(/^kind:/, "");
  if (!SUPPORTED_KINDS.has(kind)) {
    throw new Error(
      `Habitat project generator supports only uniform kinds: plugin, foundation, app. Refusing "${rawOptions.kind}" because mod, engine, control, adapter, sdk, and tooling shapes are owned by their domain maintainers.`
    );
  }

  const name = slugify(rawOptions.name);
  const pluginSlug = name.startsWith("plugin-") ? name : `plugin-${name}`;
  const root =
    rawOptions.directory ??
    (kind === "plugin"
      ? `packages/plugins/${pluginSlug}`
      : kind === "foundation"
        ? `packages/${name}`
        : `apps/${name}`);
  const packageName =
    rawOptions.packageName ??
    (kind === "plugin" ? `@civ7/${pluginSlug}` : kind === "foundation" ? `@civ7/${name}` : name);

  return {
    kind,
    tag: `kind:${kind}`,
    name,
    root: normalizePath(root),
    packageName,
  };
}

function packageJson(options) {
  return {
    name: options.packageName,
    version: "0.1.0",
    private: true,
    nx: {
      tags: [options.tag],
    },
    type: "module",
    main: "./dist/index.js",
    types: "./dist/index.d.ts",
    files: ["dist"],
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
    },
    scripts: {
      build: "tsc -p tsconfig.json",
      check: "tsc -p tsconfig.json --noEmit",
      test: "bun test",
      clean: "rimraf dist",
    },
    engines: {
      node: "22.22.0",
    },
  };
}

function tsconfigJson(options) {
  return `{
  "extends": "${relativePrefix(options.root)}tsconfig.base.json",
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "noEmit": false
  },
  "include": ["src"]
}
`;
}

function indexSource(options) {
  return `export const habitatProjectKind = "${options.tag}" as const;\n\nexport function describeHabitatProject(): string {\n  return "${options.packageName} (${options.tag})";\n}\n`;
}

function testSource(options) {
  return `import { expect, test } from "bun:test";\nimport { habitatProjectKind } from "../src/index";\n\ntest("${options.packageName} declares its Habitat kind", () => {\n  expect(habitatProjectKind).toBe("${options.tag}");\n});\n`;
}

function readme(options) {
  return `# ${options.packageName}\n\nGenerated by \`@internal/habitat-harness:project\` for \`${options.tag}\`.\n\nKeep structure changes aligned with \`docs/projects/habitat-harness/taxonomy.md\`.\n`;
}

function slugify(value) {
  const slug = String(value ?? "")
    .trim()
    .replace(/^@[^/]+\//, "")
    .replace(/[^a-zA-Z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  if (!slug) throw new Error("Project name must contain at least one alphanumeric character.");
  return slug;
}

function normalizePath(value) {
  return String(value).replace(/\\/g, "/").replace(/^\/+/, "").replace(/\/+$/g, "");
}

function relativePrefix(root) {
  return `${root
    .split("/")
    .filter(Boolean)
    .map(() => "..")
    .join("/")}/`;
}

module.exports = {
  projectGenerator,
  default: projectGenerator,
};
