export {
  FEATURE_INTENT_KEYS,
  type FeatureIntentKey,
  FeaturePlacementSchema,
  FLOODPLAIN_FEATURE_INTENT_KEYS,
  type FloodplainFeatureIntentKey,
  type FloodplainFeaturePlacement,
  FloodplainFeaturePlacementSchema,
  type IceFeatureIntentKey,
  type IceFeaturePlacement,
  IceFeaturePlacementSchema,
  type ReefFeatureIntentKey,
  type ReefFeaturePlacement,
  ReefFeaturePlacementSchema,
  type VegetationFeatureIntentKey,
  type VegetationFeaturePlacement,
  VegetationFeaturePlacementSchema,
  type WetlandFeatureIntentKey,
  type WetlandFeaturePlacement,
  WetlandFeaturePlacementSchema,
  WETLAND_FEATURE_INTENT_KEYS,
} from "./feature-placement.schema.js";
export {
  type WetlandTerrainBiomeCompatibilityMasks,
  WetlandTerrainBiomeCompatibilityMasksSchema,
} from "./wetland-terrain-biome-compatibility.schema.js";
