import { Buffer } from "node:buffer";
import { createHash, randomUUID } from "node:crypto";
import { lstat, mkdir, mkdtemp, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, sep } from "node:path";
import {
  CIV7_MAP_SCRIPT_MODULE_RESOLUTION_FILE,
  renderMapScriptModuleResolution,
} from "./module-resolution.js";
import {
  type OfficialBaseDeclarationProjection,
  projectOfficialBaseDeclarations,
} from "./projection-receipt.js";
import type { RealmClosure } from "./realms.js";
import { assertSnapshotReceipt, inspectSnapshot } from "./snapshot.js";

const GENERATED_BANNER = "This file is generated by @civ7/api-materializer. Do not edit.";

interface ProjectionTreeFile {
  readonly path: string;
  readonly size: number;
  readonly sha256: string;
}

export interface RenderedProjectionFile {
  readonly path: string;
  readonly text: string;
}

export interface ProjectionTree {
  readonly files: readonly ProjectionTreeFile[];
  readonly sha256: string;
}

export interface StagedApiProjection {
  readonly projection: OfficialBaseDeclarationProjection;
  readonly tree: ProjectionTree;
}

export interface PinnedApiProjectionOptions {
  readonly snapshotRoot: string;
  readonly destinationRoot: string;
}

export interface PinnedApiProjectionResult extends StagedApiProjection {
  readonly changed: boolean;
}

function sha256(value: string | Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

function errorCode(error: unknown): string | undefined {
  return typeof error === "object" && error !== null && "code" in error
    ? String((error as { code: unknown }).code)
    : undefined;
}

async function missingAsNull<T>(operation: () => Promise<T>): Promise<T | null> {
  try {
    return await operation();
  } catch (error) {
    if (errorCode(error) === "ENOENT") return null;
    throw error;
  }
}

function compareUtf8(left: string, right: string): number {
  return Buffer.compare(Buffer.from(left, "utf8"), Buffer.from(right, "utf8"));
}

function posixPath(value: string): string {
  return value.split(sep).join("/");
}

function generatedValue(name: string, description: string, value: unknown): string {
  return `/** ${description} */\nexport const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

function realmEntry(realmName: string): string {
  return `/// <reference path="./generated/realms/${realmName}/modules.d.ts" />\n\nexport {};\n`;
}

function realmModuleReferences(
  realm: RealmClosure,
  shardFileByModuleId: ReadonlyMap<string, string>
): string {
  const references = realm.moduleIds.map((moduleId) => {
    const fileName = shardFileByModuleId.get(moduleId);
    if (fileName === undefined) {
      throw new Error(`Realm ${realm.realm} references an unprojected declaration: ${moduleId}`);
    }
    return `/// <reference path="../../modules/${fileName}" />`;
  });
  return `${references.join("\n")}\n`;
}

function catalogValue(projection: OfficialBaseDeclarationProjection): unknown {
  const { declarations, realms } = projection;
  return {
    schemaVersion: 4,
    modules: declarations.shards.map((shard) => ({
      id: shard.virtualId,
      source: shard.sourcePath,
      declaration: `generated/modules/${shard.outputFileName}`,
      evidence: shard.evidenceKind,
      diagnostics: shard.diagnostics.length,
      anyKeywords: shard.anyKeywordCount,
      globalAugmentations: shard.globalAugmentationCount,
      dependencies: shard.edges,
    })),
    unresolvedDependencies: declarations.unresolvedTargets,
    realms: {
      roots: realms.rootEvidence,
      nonScriptMaps: realms.nonScriptMaps,
      shell: realms.shell,
      game: realms.game,
      map: realms.map,
    },
    moduleResolution: {
      mapScript: projection.receipt.moduleResolution.mapScript,
    },
  };
}

function provenanceValue(projection: OfficialBaseDeclarationProjection): unknown {
  return {
    schemaVersion: 3,
    receipt: projection.receipt,
    diagnostics: projection.declarations.shards.flatMap((shard) =>
      shard.diagnostics.map((diagnostic) => ({
        moduleId: shard.virtualId,
        source: shard.sourcePath,
        ...diagnostic,
      }))
    ),
    nonClaims: [
      "runtime-availability",
      "lifecycle",
      "dlc",
      "loading-realm",
      "absent-module-definitions",
      "unlisted-absolute-module-resolution",
      "any-free-declarations",
    ],
  };
}

/** Renders one complete generated API tree without touching the filesystem. */
function renderApiProjection(
  projection: OfficialBaseDeclarationProjection
): readonly RenderedProjectionFile[] {
  const shardFileByModuleId = new Map(
    projection.declarations.shards.map((shard) => [shard.virtualId, shard.outputFileName] as const)
  );
  const realmOutputs = [
    ["app-ui-shell", projection.realms.shell],
    ["app-ui-game", projection.realms.game],
    ["map-script", projection.realms.map],
  ] as const;
  const files: RenderedProjectionFile[] = [
    {
      path: "index.ts",
      text: `// ${GENERATED_BANNER}\nexport { catalog } from "./catalog.js";\nexport { provenance } from "./provenance.js";\n`,
    },
    {
      path: "catalog.ts",
      text: `// ${GENERATED_BANNER}\n${generatedValue("catalog", "Official Civ7 API module and realm catalog.", catalogValue(projection))}`,
    },
    {
      path: "provenance.ts",
      text: `// ${GENERATED_BANNER}\n${generatedValue("provenance", "Official Civ7 API projection provenance and diagnostics.", provenanceValue(projection))}`,
    },
    {
      path: CIV7_MAP_SCRIPT_MODULE_RESOLUTION_FILE,
      text: renderMapScriptModuleResolution(projection.mapScriptResolution),
    },
  ];
  for (const shard of projection.declarations.shards) {
    files.push({ path: `generated/modules/${shard.outputFileName}`, text: shard.text });
  }
  for (const [name, realm] of realmOutputs) {
    files.push(
      {
        path: `generated/realms/${name}/modules.d.ts`,
        text: realmModuleReferences(realm, shardFileByModuleId),
      },
      { path: `${name}.d.ts`, text: realmEntry(name) }
    );
  }
  files.sort((left, right) => compareUtf8(left.path, right.path));
  return files;
}

/** Fingerprints an in-memory rendered API tree with the disk-tree algorithm. */
export function fingerprintRenderedApiProjection(
  files: readonly RenderedProjectionFile[]
): ProjectionTree {
  const treeFiles = files.map((file) => {
    const bytes = Buffer.from(file.text, "utf8");
    return { path: file.path, size: bytes.byteLength, sha256: sha256(bytes) };
  });
  return {
    files: treeFiles,
    sha256: sha256(
      treeFiles.map((file) => `${file.path}\0${file.size}\0${file.sha256}\n`).join("")
    ),
  };
}

async function writeRenderedApiProjection(
  outputRoot: string,
  files: readonly RenderedProjectionFile[]
): Promise<void> {
  await rm(outputRoot, { recursive: true, force: true });
  for (const file of files) {
    const path = join(outputRoot, file.path);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, file.text);
  }
}

/** Fingerprints one generated API source tree in deterministic UTF-8 order. */
export async function inspectApiProjection(root: string): Promise<ProjectionTree> {
  const files: ProjectionTreeFile[] = [];
  const visit = async (directory: string): Promise<void> => {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => compareUtf8(left.name, right.name));
    for (const entry of entries) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) {
        await visit(path);
      } else if (entry.isFile()) {
        const bytes = await readFile(path);
        files.push({
          path: posixPath(relative(root, path)),
          size: bytes.byteLength,
          sha256: sha256(bytes),
        });
      } else {
        throw new Error(`Unsupported generated API filesystem entry: ${path}`);
      }
    }
  };
  await visit(root);
  files.sort((left, right) => compareUtf8(left.path, right.path));
  return {
    files,
    sha256: sha256(files.map((file) => `${file.path}\0${file.size}\0${file.sha256}\n`).join("")),
  };
}

/** Projects the validated pinned snapshot into one complete generated API source tree. */
export async function stageApiProjection(
  snapshotRoot: string,
  outputRoot: string
): Promise<StagedApiProjection> {
  const rendered = await renderPinnedApiProjection(snapshotRoot);
  await writeRenderedApiProjection(outputRoot, rendered.files);
  const writtenTree = await inspectApiProjection(outputRoot);
  if (!apiProjectionTreesMatch(rendered.tree, writtenTree)) {
    throw new Error("Written Civ7 API projection differs from its in-memory render");
  }
  return { projection: rendered.projection, tree: rendered.tree };
}

async function renderPinnedApiProjection(
  snapshotRoot: string
): Promise<StagedApiProjection & { readonly files: readonly RenderedProjectionFile[] }> {
  const snapshot = await inspectSnapshot(snapshotRoot);
  assertSnapshotReceipt(snapshot);
  const projection = await projectOfficialBaseDeclarations(snapshotRoot);
  const files = renderApiProjection(projection);
  const tree = fingerprintRenderedApiProjection(files);
  return { projection, tree, files };
}

export function apiProjectionTreesMatch(left: ProjectionTree, right: ProjectionTree): boolean {
  return left.sha256 === right.sha256 && left.files.length === right.files.length;
}

function projectionDifference(expected: ProjectionTree, actual: ProjectionTree | null): string {
  if (actual === null) return "generated API source is absent";
  const paths = new Set([
    ...expected.files.map((file) => file.path),
    ...actual.files.map((file) => file.path),
  ]);
  for (const path of [...paths].sort(compareUtf8)) {
    const expectedFile = expected.files.find((file) => file.path === path);
    const actualFile = actual.files.find((file) => file.path === path);
    if (expectedFile?.sha256 !== actualFile?.sha256 || expectedFile?.size !== actualFile?.size) {
      return `${path}: expected ${expectedFile?.sha256 ?? "absent"}, found ${actualFile?.sha256 ?? "absent"}`;
    }
  }
  return `expected ${expected.sha256}, found ${actual.sha256}`;
}

/** Returns the stable recovery path for one generated API source replacement. */
export function generatedApiBackupRoot(destinationRoot: string): string {
  return join(dirname(destinationRoot), `.${basename(destinationRoot)}.materializer-backup`);
}

interface GeneratedApiReplacementMarker {
  readonly schemaVersion: 1;
  readonly destinationExisted: boolean;
}

/** Returns the stable commit-marker path for one generated API source replacement. */
export function generatedApiReplacementMarkerPath(destinationRoot: string): string {
  return join(
    dirname(destinationRoot),
    `.${basename(destinationRoot)}.materializer-transaction.json`
  );
}

function parseGeneratedApiReplacementMarker(
  text: string,
  path: string
): GeneratedApiReplacementMarker {
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch (error) {
    throw new Error(`Invalid generated Civ7 API replacement marker: ${path}`, { cause: error });
  }
  if (
    typeof value !== "object" ||
    value === null ||
    (value as { schemaVersion?: unknown }).schemaVersion !== 1 ||
    typeof (value as { destinationExisted?: unknown }).destinationExisted !== "boolean"
  ) {
    throw new Error(`Invalid generated Civ7 API replacement marker: ${path}`);
  }
  return value as GeneratedApiReplacementMarker;
}

async function writeGeneratedApiReplacementMarker(
  markerPath: string,
  marker: GeneratedApiReplacementMarker
): Promise<void> {
  const tempPath = `${markerPath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(tempPath, `${JSON.stringify(marker, null, 2)}\n`, { flag: "wx" });
    await rename(tempPath, markerPath);
  } finally {
    await rm(tempPath, { force: true });
  }
}

async function pathExists(path: string): Promise<boolean> {
  return (await missingAsNull(() => lstat(path))) !== null;
}

/** Recovers or finalizes an interrupted API-only replacement. */
export async function recoverGeneratedApiReplacement(destinationRoot: string): Promise<void> {
  const backupRoot = generatedApiBackupRoot(destinationRoot);
  const markerPath = generatedApiReplacementMarkerPath(destinationRoot);
  const markerText = await missingAsNull(() => readFile(markerPath, "utf8"));
  if (markerText !== null) {
    const marker = parseGeneratedApiReplacementMarker(markerText, markerPath);
    const [backupExists, destinationExists] = await Promise.all([
      pathExists(backupRoot),
      pathExists(destinationRoot),
    ]);
    if (marker.destinationExisted) {
      if (backupExists) {
        await rm(destinationRoot, { recursive: true, force: true });
        await rename(backupRoot, destinationRoot);
      } else if (!destinationExists) {
        throw new Error(`Generated Civ7 API replacement lost both destination and backup`);
      }
    } else {
      if (backupExists) {
        throw new Error(`Generated Civ7 API replacement created an impossible backup`);
      }
      await rm(destinationRoot, { recursive: true, force: true });
    }
    await rm(markerPath, { force: true });
    return;
  }

  if (!(await pathExists(backupRoot))) return;
  if (!(await pathExists(destinationRoot))) {
    await rename(backupRoot, destinationRoot);
    return;
  }
  await rm(backupRoot, { recursive: true, force: true });
}

/** Refuses an interrupted API replacement without changing repository state. */
export async function assertGeneratedApiReplacementSettled(destinationRoot: string): Promise<void> {
  const residue = (
    await Promise.all(
      [
        generatedApiReplacementMarkerPath(destinationRoot),
        generatedApiBackupRoot(destinationRoot),
      ].map(async (path) => ((await pathExists(path)) ? [path] : []))
    )
  ).flat();
  if (residue.length > 0) {
    throw new Error(
      `Generated Civ7 API replacement is in progress or interrupted: ${residue.join(", ")}; run api:generate to recover`
    );
  }
}

/** Atomically replaces only the generated package source after complete staging. */
export async function replaceGeneratedApiSource(
  stagedRoot: string,
  destinationRoot: string,
  verify: (root: string) => Promise<void> = async () => undefined
): Promise<void> {
  await recoverGeneratedApiReplacement(destinationRoot);
  const backupRoot = generatedApiBackupRoot(destinationRoot);
  const markerPath = generatedApiReplacementMarkerPath(destinationRoot);
  const hadDestination = await pathExists(destinationRoot);
  try {
    await writeGeneratedApiReplacementMarker(markerPath, {
      schemaVersion: 1,
      destinationExisted: hadDestination,
    });
    if (hadDestination) await rename(destinationRoot, backupRoot);
    await rename(stagedRoot, destinationRoot);
    await verify(destinationRoot);
    await rm(markerPath, { force: true });
  } catch (error) {
    await recoverGeneratedApiReplacement(destinationRoot);
    throw error;
  }
  await rm(backupRoot, { recursive: true, force: true });
}

/** Verifies the pinned API entirely in memory and never repairs repository state. */
export async function checkPinnedApiProjection(
  options: PinnedApiProjectionOptions
): Promise<PinnedApiProjectionResult> {
  await assertGeneratedApiReplacementSettled(options.destinationRoot);
  const rendered = await renderPinnedApiProjection(options.snapshotRoot);
  const current = await missingAsNull(() => inspectApiProjection(options.destinationRoot));
  await assertGeneratedApiReplacementSettled(options.destinationRoot);
  if (current === null || !apiProjectionTreesMatch(rendered.tree, current)) {
    throw new Error(
      `Generated Civ7 API projection is stale: ${projectionDifference(rendered.tree, current)}`
    );
  }
  return { projection: rendered.projection, tree: rendered.tree, changed: false };
}

/** Generates the API strictly from the pinned official snapshot. */
export async function materializePinnedApiProjection(
  options: PinnedApiProjectionOptions
): Promise<PinnedApiProjectionResult> {
  await recoverGeneratedApiReplacement(options.destinationRoot);
  const stageRoot = await mkdtemp(join(dirname(options.destinationRoot), ".civ7-api-projection-"));
  try {
    const staged = await stageApiProjection(options.snapshotRoot, stageRoot);
    const current = await missingAsNull(() => inspectApiProjection(options.destinationRoot));
    if (current !== null && apiProjectionTreesMatch(staged.tree, current)) {
      return { ...staged, changed: false };
    }
    await replaceGeneratedApiSource(stageRoot, options.destinationRoot, async (root) => {
      const replaced = await inspectApiProjection(root);
      if (!apiProjectionTreesMatch(staged.tree, replaced)) {
        throw new Error(
          `Replaced Civ7 API differs from its validated stage: ${projectionDifference(staged.tree, replaced)}`
        );
      }
    });
    return { ...staged, changed: true };
  } finally {
    await rm(stageRoot, { recursive: true, force: true });
  }
}
