import path from "node:path";
import { type WriteProjectScaffoldDecision } from "@internal/habitat-harness/generators/scaffold/model";
import { type Tree, writeJson } from "@nx/devkit";

export function writeProjectScaffold(tree: Tree, decision: WriteProjectScaffoldDecision): void {
  const options = decision.request;
  writeJson(tree, path.posix.join(options.root, "package.json"), packageJson(options));
  tree.write(path.posix.join(options.root, "tsconfig.json"), tsconfigJson(options.root));
  tree.write(path.posix.join(options.root, "src", "index.ts"), indexSource(options));
  tree.write(path.posix.join(options.root, "test", "index.test.ts"), testSource(options));
  tree.write(path.posix.join(options.root, "README.md"), readme(options));
}

function packageJson(options: WriteProjectScaffoldDecision["request"]) {
  return {
    name: options.packageName,
    version: "0.1.0",
    private: true,
    nx: {
      tags: [options.tag],
    },
    type: "module",
    main: "./dist/index.js",
    types: "./dist/index.d.ts",
    files: ["dist"],
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
    },
    scripts: {
      build: "tsc -p tsconfig.json",
      check: "tsc -p tsconfig.json --noEmit",
      test: "bun test",
      clean: "rimraf dist",
    },
    engines: {
      node: "22.22.0",
    },
  };
}

function tsconfigJson(root: string): string {
  return `{
  "extends": "${relativePrefix(root)}tsconfig.base.json",
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "noEmit": false
  },
  "include": ["src"]
}
`;
}

function indexSource(options: WriteProjectScaffoldDecision["request"]): string {
  return `export const habitatProjectKind = "${options.tag}" as const;\n\nexport function describeHabitatProject(): string {\n  return "${options.packageName} (${options.tag})";\n}\n`;
}

function testSource(options: WriteProjectScaffoldDecision["request"]): string {
  return `import { expect, test } from "bun:test";\nimport { habitatProjectKind } from "../src/index";\n\ntest("${options.packageName} declares its Habitat kind", () => {\n  expect(habitatProjectKind).toBe("${options.tag}");\n});\n`;
}

function readme(options: WriteProjectScaffoldDecision["request"]): string {
  return `# ${options.packageName}\n\nGenerated by \`@internal/habitat-harness:project\` for \`${options.tag}\`.\n\nKeep structure changes aligned with \`docs/projects/habitat-harness/taxonomy.md\`.\n`;
}

function relativePrefix(root: string): string {
  return `${root
    .split("/")
    .filter(Boolean)
    .map(() => "..")
    .join("/")}/`;
}
