export const DEFAULT_CIV7_TUNER_HOST = "127.0.0.1";
export const DEFAULT_CIV7_TUNER_PORT = 4318;
export const DEFAULT_CIV7_TUNER_TIMEOUT_MS = 10_000;
export const DEFAULT_CIV7_TUNER_STATE_NAME = "App UI";
export const CIV7_TUNER_APP_UI_STATE_NAME = "App UI";
export const CIV7_TUNER_STATE_NAME = "Tuner";
