/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: `bun scripts/mapgen-studio/generate-civ7-browser-tables.ts`
 * Source of truth: `Base/modules/base-standard/data/terrain.xml` (under `.civ7/outputs/resources`)
 *
 * Purpose:
 * - Provide Civ7-derived indices (terrain/biome/feature) as a bundled, browser-importable module.
 * - The Web Worker must not fetch these at runtime.
 */

export const CIV7_BROWSER_TABLES_V0 = {
  version: 0 as const,
  source: "Base/modules/base-standard/data/terrain.xml" as const,
  terrainTypeIndices: {
  "TERRAIN_COAST": 3,
  "TERRAIN_FLAT": 2,
  "TERRAIN_HILL": 1,
  "TERRAIN_MOUNTAIN": 0,
  "TERRAIN_NAVIGABLE_RIVER": 5,
  "TERRAIN_OCEAN": 4,
} as const,
  biomeGlobals: {
  "BIOME_DESERT": 4,
  "BIOME_GRASSLAND": 1,
  "BIOME_MARINE": 5,
  "BIOME_PLAINS": 2,
  "BIOME_TROPICAL": 3,
  "BIOME_TUNDRA": 0,
} as const,
  featureTypes: {
  "FEATURE_ATOLL": 25,
  "FEATURE_BARRIER_REEF": 27,
  "FEATURE_COLD_REEF": 9,
  "FEATURE_DESERT_FLOODPLAIN_MINOR": 2,
  "FEATURE_DESERT_FLOODPLAIN_NAVIGABLE": 3,
  "FEATURE_FOREST": 4,
  "FEATURE_GRAND_CANYON": 29,
  "FEATURE_GRASSLAND_FLOODPLAIN_MINOR": 6,
  "FEATURE_GRASSLAND_FLOODPLAIN_NAVIGABLE": 7,
  "FEATURE_GULLFOSS": 30,
  "FEATURE_HOERIKWAGGO": 31,
  "FEATURE_ICE": 10,
  "FEATURE_IGUAZU_FALLS": 32,
  "FEATURE_KILIMANJARO": 33,
  "FEATURE_LOTUS": 24,
  "FEATURE_MANGROVE": 16,
  "FEATURE_MARSH": 5,
  "FEATURE_OASIS": 1,
  "FEATURE_PLAINS_FLOODPLAIN_MINOR": 13,
  "FEATURE_PLAINS_FLOODPLAIN_NAVIGABLE": 14,
  "FEATURE_RAINFOREST": 15,
  "FEATURE_REDWOOD_FOREST": 28,
  "FEATURE_REEF": 8,
  "FEATURE_SAGEBRUSH_STEPPE": 0,
  "FEATURE_SAVANNA_WOODLAND": 11,
  "FEATURE_TAIGA": 19,
  "FEATURE_THERA": 35,
  "FEATURE_TORRES_DEL_PAINE": 36,
  "FEATURE_TROPICAL_FLOODPLAIN_MINOR": 17,
  "FEATURE_TROPICAL_FLOODPLAIN_NAVIGABLE": 18,
  "FEATURE_TUNDRA_BOG": 20,
  "FEATURE_TUNDRA_FLOODPLAIN_MINOR": 21,
  "FEATURE_TUNDRA_FLOODPLAIN_NAVIGABLE": 22,
  "FEATURE_ULURU": 37,
  "FEATURE_VALLEY_OF_FLOWERS": 26,
  "FEATURE_VOLCANO": 23,
  "FEATURE_WATERING_HOLE": 12,
  "FEATURE_ZHANGJIAJIE": 34,
} as const,
} as const;

export type Civ7BrowserTablesV0 = typeof CIV7_BROWSER_TABLES_V0;
