export type {
  DependencyUnavailableData,
  ExpectedFailureErrorData,
  FailedErrorData,
  StatusNotFoundData,
  StatusNotFoundErrorData,
  StudioBoundedDiagnostics,
  StudioBoundedDiagnosticValue,
  StudioFailureData,
  StudioRecoveryAction,
  StudioRuntimeFailure,
  UnavailableFailureErrorData,
  UnexpectedDefectData,
} from "@civ7/studio-contract";
export {
  autoplayStartStopFailed,
  autoplayVerificationFailed,
  daemonIdentityMismatch,
  dependencyUnavailable,
  deployFailed,
  expectedFailureDataSchema,
  expectedFailureErrorDataSchema,
  failedErrorDataSchema,
  invalidRequest,
  isStudioRuntimeFailure,
  materializationFailed,
  operationBlocked,
  operationExpired,
  operationNotFound,
  preventStudioRuntimeFailureReplay,
  runtimeDisposed,
  STUDIO_FAILURE_REASON_CODES,
  STUDIO_FAILURE_TAGS,
  STUDIO_OPERATION_NAMESPACES,
  STUDIO_RECOVERY_ACTIONS,
  statusNotFoundErrorDataSchema,
  studioFailureDataSchema,
  studioRecoveryActionSchema,
  unavailableFailureErrorDataSchema,
  unsupportedOperationType,
  verificationFailed,
} from "@civ7/studio-contract";
export type {
  StudioDeclaredErrorCode,
  StudioDefinedErrorProjection,
  StudioOperationProcedure,
} from "./mapping.js";
export {
  mapStudioFailureToDefinedError,
  mapUnexpectedDefectToDefinedError,
  mapUnknownToStudioDefinedError,
  STUDIO_OPERATION_PROCEDURES,
  toStudioDefinedOrpcError,
} from "./mapping.js";
