import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type ExtractedTables = {
  terrainTypeOrder: string[];
  biomeOrder: string[];
  featureOrder: string[];
  sources: string[];
};

function fatal(message: string): never {
  console.error(message);
  process.exit(1);
}

function extractXmlSection(xml: string, tag: string): string {
  const re = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, "m");
  const m = re.exec(xml);
  if (!m?.[1]) fatal(`[civ7-tables] missing <${tag}> section`);
  return m[1];
}

function extractRowAttr(sectionXml: string, attr: string): string[] {
  const out: string[] = [];
  const re = new RegExp(`<Row\\s+[^>]*${attr}="([^"]+)"[^>]*/>`, "g");
  let m: RegExpExecArray | null;
  while ((m = re.exec(sectionXml))) {
    const v = m[1];
    if (v) out.push(v);
  }
  return out;
}

function assertNoDuplicates(label: string, values: string[]): void {
  const seen = new Set<string>();
  const dupes = new Set<string>();
  for (const v of values) {
    if (seen.has(v)) dupes.add(v);
    seen.add(v);
  }
  if (dupes.size) fatal(`[civ7-tables] duplicate ${label}: ${[...dupes].join(", ")}`);
}

function indexByOrder(values: string[]): Record<string, number> {
  return Object.fromEntries(values.map((v, i) => [v, i]));
}

function appendUnique(out: string[], values: string[]): void {
  const seen = new Set(out);
  for (const value of values) {
    if (seen.has(value)) fatal(`[civ7-tables] duplicate features: ${value}`);
    seen.add(value);
    out.push(value);
  }
}

function parseTerrainXml(xml: string): Pick<ExtractedTables, "terrainTypeOrder" | "biomeOrder"> {
  const terrains = extractRowAttr(extractXmlSection(xml, "Terrains"), "TerrainType");
  const biomes = extractRowAttr(extractXmlSection(xml, "Biomes"), "BiomeType");

  if (!terrains.length) fatal("[civ7-tables] no terrain rows found");
  if (!biomes.length) fatal("[civ7-tables] no biome rows found");

  assertNoDuplicates("terrain types", terrains);
  assertNoDuplicates("biomes", biomes);

  return {
    terrainTypeOrder: terrains,
    biomeOrder: biomes,
  };
}

function parseFeatureXml(xml: string, relPath: string): string[] {
  const features = extractRowAttr(extractXmlSection(xml, "Features"), "FeatureType");
  if (!features.length) fatal(`[civ7-tables] no feature rows found in ${relPath}`);
  assertNoDuplicates(`features in ${relPath}`, features);
  return features;
}

function toTsObjectLiteral(obj: Record<string, number>): string {
  const lines = Object.keys(obj)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${obj[k]},`);
  return `{\n${lines.join("\n")}\n}`;
}

function main(): void {
  const repoRoot = process.cwd();
  const terrainXmlRelPath = "Base/modules/base-standard/data/terrain.xml";
  const featureXmlRelPaths = [
    "Base/modules/base-standard/data/racetowonders-terrain.xml",
    "Base/modules/base-standard/data/marvelous-mountains-terrain.xml",
    terrainXmlRelPath,
    "DLC/mountain-natural-wonders/modules/data/terrain.xml",
    "DLC/water-wonders/modules/data/terrain.xml",
  ];
  const terrainXmlPath = resolve(repoRoot, ".civ7/outputs/resources", terrainXmlRelPath);
  const adapterOutPath = resolve(repoRoot, "packages/civ7-adapter/src/civ7-tables.gen.ts");
  const outPath = resolve(repoRoot, "apps/mapgen-studio/src/civ7-data/civ7-tables.gen.ts");

  const xml = readFileSync(terrainXmlPath, "utf8");
  const terrainAndBiome = parseTerrainXml(xml);
  const featureOrder: string[] = [];
  for (const relPath of featureXmlRelPaths) {
    const path = resolve(repoRoot, ".civ7/outputs/resources", relPath);
    if (!existsSync(path)) fatal(`[civ7-tables] missing source file: ${relPath}`);
    appendUnique(featureOrder, parseFeatureXml(readFileSync(path, "utf8"), relPath));
  }
  const extracted: ExtractedTables = {
    ...terrainAndBiome,
    featureOrder,
    sources: featureXmlRelPaths,
  };

  const terrainTypeIndices = indexByOrder(extracted.terrainTypeOrder);
  const biomeGlobals = indexByOrder(extracted.biomeOrder);
  const featureTypes = indexByOrder(extracted.featureOrder);

  if (featureTypes.FEATURE_BERMUDA_TRIANGLE !== 0 || featureTypes.FEATURE_MOUNT_EVEREST !== 1) {
    fatal("[civ7-tables] feature order does not match live GameInfo.Features natural-wonder prefix");
  }
  if (featureTypes.FEATURE_SAGEBRUSH_STEPPE !== 2 || featureTypes.FEATURE_MAPU_A_VAEA_BLOWHOLES !== 45) {
    fatal("[civ7-tables] feature order does not match live GameInfo.Features base/DLC ordering");
  }

  mkdirSync(dirname(outPath), { recursive: true });
  mkdirSync(dirname(adapterOutPath), { recursive: true });

  const adapterFile = `/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: \`bun scripts/mapgen-studio/generate-civ7-browser-tables.ts\`
 * Source of truth: Civ7 official resource XML under \`.civ7/outputs/resources\`
 *
 * Purpose:
 * - Provide Civ7-derived terrain/biome/feature indices for mock generation.
 * - Keep browser Studio, diagnostics, and adapter mocks on the same GameInfo order.
 */

export const CIV7_BROWSER_TABLES_V0 = {
  version: 0 as const,
  source: ${JSON.stringify(extracted.sources, null, 2)} as const,
  terrainTypeIndices: ${toTsObjectLiteral(terrainTypeIndices)} as const,
  biomeGlobals: ${toTsObjectLiteral(biomeGlobals)} as const,
  featureTypes: ${toTsObjectLiteral(featureTypes)} as const,
} as const;

export type Civ7BrowserTablesV0 = typeof CIV7_BROWSER_TABLES_V0;
`;

  const appFile = `/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by: \`bun scripts/mapgen-studio/generate-civ7-browser-tables.ts\`
 * Source of truth: \`@civ7/adapter\` generated Civ7 table contract.
 */

export { CIV7_BROWSER_TABLES_V0 } from "@civ7/adapter";
export type { Civ7BrowserTablesV0 } from "@civ7/adapter";
`;

  writeFileSync(adapterOutPath, adapterFile);
  writeFileSync(outPath, appFile);
  console.log(`[civ7-tables] wrote ${adapterOutPath}`);
  console.log(`[civ7-tables] wrote ${outPath}`);
}

main();
