import {
  admitCiv7SetupShell,
  applyCiv7ExploreGrant,
  applyCiv7SinglePlayerSetupIdentity,
  applyCiv7SinglePlayerSetupOptions,
  beginCiv7Game,
  type Civ7ComponentId,
  type Civ7DirectControlOptions,
  type Civ7SavedGameConfigurationRef,
  captureCiv7WindowShot,
  checkCiv7AdvisorWarningViewed,
  checkCiv7AttributePurchase,
  checkCiv7AttributeReview,
  checkCiv7CelebrationChoice,
  checkCiv7CityExpansion,
  checkCiv7DiplomacyResponse,
  checkCiv7FirstMeetResponse,
  checkCiv7GovernmentChoice,
  checkCiv7NarrativeChoice,
  checkCiv7NotificationDismissal,
  checkCiv7ProductionChoice,
  checkCiv7ProgressionTreeChoice,
  checkCiv7ProgressionTreeTarget,
  checkCiv7TownFocusChange,
  checkCiv7TownFocusReview,
  checkCiv7TraditionChange,
  checkCiv7TraditionReview,
  checkCiv7TunerHealth,
  checkCiv7TurnCompletion,
  checkCiv7UnitResettle,
  checkCiv7UnitTargetAction,
  checkCiv7UnitUpgrade,
  checkCiv7WorkerAssignment,
  clearCiv7ProgressionTreeTarget,
  closeCiv7Displays,
  enterCiv7CleanFrame,
  exitCiv7CleanFrame,
  focusCiv7CameraOnPlot,
  getCiv7AppUiSnapshot,
  getCiv7BattlefieldScan,
  getCiv7DestinationAnalysis,
  getCiv7MapGrid,
  getCiv7MapSummary,
  getCiv7PlayableStatus,
  getCiv7PlayNotificationView,
  getCiv7PlotSnapshot,
  getCiv7ProgressDashboard,
  getCiv7ReadyCityView,
  getCiv7ReadyUnitView,
  getCiv7SelectedSetupSnapshot,
  getCiv7SettlementRecommendations,
  getCiv7SetupMapRows,
  getCiv7TargetCandidates,
  getCiv7TraditionsView,
  getCiv7VisibilitySummary,
  hostPreparedCiv7SinglePlayerGame,
  observeCiv7AttributeNode,
  observeCiv7TraditionAssignments,
  observeCiv7UnitTarget,
  readCiv7DisplayQueue,
  reconcileCiv7RequiredTargetMod,
  releaseCiv7ExploreGrant,
  reloadCiv7SetupUiInShell,
  requestCiv7SavedGameConfigurationLoad,
  resumeCiv7DisplayQueue,
  sendCiv7AdvisorWarningViewed,
  sendCiv7AttributePurchase,
  sendCiv7AttributeReview,
  sendCiv7CelebrationChoice,
  sendCiv7CityExpansion,
  sendCiv7DiplomacyResponse,
  sendCiv7FirstMeetResponse,
  sendCiv7GovernmentChoice,
  sendCiv7NarrativeChoice,
  sendCiv7NotificationDismissal,
  sendCiv7ProductionChoice,
  sendCiv7ProgressionTreeChoice,
  sendCiv7ProgressionTreeTarget,
  sendCiv7TownFocusChange,
  sendCiv7TownFocusReview,
  sendCiv7TraditionChange,
  sendCiv7TraditionReview,
  sendCiv7TurnCompletion,
  sendCiv7UnitResettle,
  sendCiv7UnitTargetAction,
  sendCiv7UnitUpgrade,
  sendCiv7WorkerAssignment,
  suspendCiv7DisplayQueue,
} from "./index.js";

/** Provider-neutral live direct-control atoms for qualified host composition. */
export const liveCiv7DirectControl = {
  observeCiv7AttributeNode,
  checkCiv7AttributePurchase,
  sendCiv7AttributePurchase,
  checkCiv7AttributeReview,
  sendCiv7AttributeReview,
  checkCiv7ProgressionTreeChoice,
  sendCiv7ProgressionTreeChoice,
  checkCiv7ProgressionTreeTarget,
  sendCiv7ProgressionTreeTarget,
  clearCiv7ProgressionTreeTarget,
  observeCiv7TraditionAssignments,
  checkCiv7TraditionChange,
  sendCiv7TraditionChange,
  checkCiv7TraditionReview,
  sendCiv7TraditionReview,
  checkCiv7WorkerAssignment,
  sendCiv7WorkerAssignment,
  checkCiv7CityExpansion,
  sendCiv7CityExpansion,
  checkCiv7ProductionChoice,
  sendCiv7ProductionChoice,
  checkCiv7FirstMeetResponse,
  sendCiv7FirstMeetResponse,
  checkCiv7DiplomacyResponse,
  sendCiv7DiplomacyResponse,
  checkCiv7GovernmentChoice,
  sendCiv7GovernmentChoice,
  checkCiv7CelebrationChoice,
  sendCiv7CelebrationChoice,
  checkCiv7NarrativeChoice,
  sendCiv7NarrativeChoice,
  checkCiv7TownFocusChange,
  sendCiv7TownFocusChange,
  checkCiv7TownFocusReview,
  sendCiv7TownFocusReview,
  checkCiv7NotificationDismissal,
  sendCiv7NotificationDismissal,
  checkCiv7AdvisorWarningViewed,
  sendCiv7AdvisorWarningViewed,
  observeCiv7UnitTarget,
  checkCiv7UnitTargetAction,
  sendCiv7UnitTargetAction,
  checkCiv7UnitUpgrade,
  sendCiv7UnitUpgrade,
  checkCiv7UnitResettle,
  sendCiv7UnitResettle,
  checkCiv7TurnCompletion,
  sendCiv7TurnCompletion,
  getCiv7PlayableStatus,
  getCiv7PlayNotificationView,
  getCiv7ProgressDashboard,
  getCiv7TraditionsView,
  getCiv7BattlefieldScan,
  getCiv7DestinationAnalysis,
  getCiv7PlotSnapshot,
  getCiv7MapGrid,
  getCiv7ReadyUnitView,
  getCiv7ReadyCityView,
  getCiv7SettlementRecommendations,
  getCiv7TargetCandidates,
  getCiv7VisibilitySummary,
  readCiv7DisplayQueue,
  closeCiv7Displays,
  suspendCiv7DisplayQueue,
  resumeCiv7DisplayQueue,
  applyCiv7ExploreGrant,
  releaseCiv7ExploreGrant,
  focusCiv7Camera: focusCiv7CameraOnPlot,
  enterCiv7CleanFrame,
  exitCiv7CleanFrame,
  captureCiv7WindowShot,
};

type Civ7SavedConfigIdentity = Omit<Civ7SavedGameConfigurationRef, "path">;

/** Provider-neutral live setup lifecycle atoms for qualified host composition. */
export const liveCiv7LifecycleControl = {
  getSetupSnapshot: getCiv7SelectedSetupSnapshot,
  admitSetupShell: admitCiv7SetupShell,
  requestSavedConfigLoad: (input: Civ7SavedConfigIdentity, options?: Civ7DirectControlOptions) =>
    requestCiv7SavedGameConfigurationLoad({ ...input, path: input.fileName }, options),
  reconcileRequiredTargetMod: reconcileCiv7RequiredTargetMod,
  getSetupMapRows: getCiv7SetupMapRows,
  reloadSetupUiInShell: reloadCiv7SetupUiInShell,
  applySinglePlayerSetupIdentity: applyCiv7SinglePlayerSetupIdentity,
  applySinglePlayerSetupOptions: applyCiv7SinglePlayerSetupOptions,
  hostPreparedSinglePlayerGame: hostPreparedCiv7SinglePlayerGame,
  getAppUiSnapshot: getCiv7AppUiSnapshot,
  beginGame: beginCiv7Game,
  checkTunerHealth: checkCiv7TunerHealth,
  getMapSummary: getCiv7MapSummary,
};
