import {
  admitCiv7SetupShell,
  applyCiv7ExploreGrant,
  applyCiv7SinglePlayerSetupIdentity,
  applyCiv7SinglePlayerSetupOptions,
  beginCiv7Game,
  type Civ7ComponentId,
  type Civ7DirectControlOptions,
  type Civ7SavedGameConfigurationRef,
  captureCiv7WindowShot,
  checkCiv7CelebrationChoice,
  checkCiv7CityExpansion,
  checkCiv7GovernmentChoice,
  checkCiv7NarrativeChoice,
  checkCiv7ProductionChoice,
  checkCiv7TownFocusChange,
  checkCiv7TownFocusReview,
  checkCiv7TunerHealth,
  checkCiv7TurnCompletion,
  checkCiv7UnitResettle,
  checkCiv7UnitUpgrade,
  checkCiv7WorkerAssignment,
  closeCiv7Displays,
  enterCiv7CleanFrame,
  exitCiv7CleanFrame,
  focusCiv7CameraOnPlot,
  getCiv7AppUiSnapshot,
  getCiv7BattlefieldScan,
  getCiv7DestinationAnalysis,
  getCiv7MapGrid,
  getCiv7MapSummary,
  getCiv7PlayableStatus,
  getCiv7PlayNotificationView,
  getCiv7PlotSnapshot,
  getCiv7ProgressDashboard,
  getCiv7ReadyCityView,
  getCiv7ReadyUnitView,
  getCiv7SettlementRecommendations,
  getCiv7SetupMapRows,
  getCiv7SetupSnapshot,
  getCiv7TargetCandidates,
  getCiv7TraditionsView,
  getCiv7VisibilitySummary,
  hostPreparedCiv7SinglePlayerGame,
  readCiv7DisplayQueue,
  reconcileCiv7RequiredTargetMod,
  releaseCiv7ExploreGrant,
  reloadCiv7SetupUiInShell,
  requestCiv7AdvisorWarningViewed,
  requestCiv7AttributePurchase,
  requestCiv7AttributeReviewCloseout,
  requestCiv7CultureChoiceCloseout,
  requestCiv7CultureTarget,
  requestCiv7DiplomacyResponse,
  requestCiv7FirstMeetResponse,
  requestCiv7NotificationDismissal,
  requestCiv7SavedGameConfigurationLoad,
  requestCiv7TechnologyChoiceCloseout,
  requestCiv7TechnologyTarget,
  requestCiv7TraditionChange,
  requestCiv7TraditionReviewCloseout,
  requestCiv7UnitTargetAction,
  resumeCiv7DisplayQueue,
  sendCiv7CelebrationChoice,
  sendCiv7CityExpansion,
  sendCiv7GovernmentChoice,
  sendCiv7NarrativeChoice,
  sendCiv7ProductionChoice,
  sendCiv7TownFocusChange,
  sendCiv7TownFocusReview,
  sendCiv7TurnCompletion,
  sendCiv7UnitResettle,
  sendCiv7UnitUpgrade,
  sendCiv7WorkerAssignment,
  suspendCiv7DisplayQueue,
} from "./index.js";

/** Provider-neutral live direct-control atoms for qualified host composition. */
export const liveCiv7DirectControl = {
  checkCiv7WorkerAssignment,
  sendCiv7WorkerAssignment,
  checkCiv7CityExpansion,
  sendCiv7CityExpansion,
  checkCiv7ProductionChoice,
  sendCiv7ProductionChoice,
  checkCiv7GovernmentChoice,
  sendCiv7GovernmentChoice,
  checkCiv7CelebrationChoice,
  sendCiv7CelebrationChoice,
  checkCiv7NarrativeChoice,
  sendCiv7NarrativeChoice,
  checkCiv7TownFocusChange,
  sendCiv7TownFocusChange,
  checkCiv7TownFocusReview,
  sendCiv7TownFocusReview,
  requestCiv7NotificationDismissal,
  requestCiv7AdvisorWarningViewed,
  requestCiv7DiplomacyResponse,
  requestCiv7FirstMeetResponse,
  requestCiv7TechnologyChoiceCloseout,
  requestCiv7CultureChoiceCloseout,
  requestCiv7TechnologyTarget,
  requestCiv7CultureTarget,
  requestCiv7AttributePurchase,
  requestCiv7AttributeReviewCloseout,
  requestCiv7TraditionChange,
  requestCiv7TraditionReviewCloseout,
  requestCiv7UnitTargetAction,
  checkCiv7UnitUpgrade,
  sendCiv7UnitUpgrade,
  checkCiv7UnitResettle,
  sendCiv7UnitResettle,
  checkCiv7TurnCompletion,
  sendCiv7TurnCompletion,
  getCiv7PlayableStatus,
  getCiv7PlayNotificationView,
  getCiv7ProgressDashboard,
  getCiv7TraditionsView,
  getCiv7BattlefieldScan,
  getCiv7DestinationAnalysis,
  getCiv7PlotSnapshot,
  getCiv7MapGrid,
  getCiv7ReadyUnitView,
  getCiv7ReadyCityView,
  getCiv7SettlementRecommendations,
  getCiv7TargetCandidates,
  getCiv7VisibilitySummary,
  readCiv7DisplayQueue,
  closeCiv7Displays,
  suspendCiv7DisplayQueue,
  resumeCiv7DisplayQueue,
  applyCiv7ExploreGrant,
  releaseCiv7ExploreGrant,
  focusCiv7Camera: focusCiv7CameraOnPlot,
  enterCiv7CleanFrame,
  exitCiv7CleanFrame,
  captureCiv7WindowShot,
};

type Civ7SavedConfigIdentity = Omit<Civ7SavedGameConfigurationRef, "path">;

/** Provider-neutral live setup lifecycle atoms for qualified host composition. */
export const liveCiv7LifecycleControl = {
  getSetupSnapshot: getCiv7SetupSnapshot,
  admitSetupShell: admitCiv7SetupShell,
  requestSavedConfigLoad: (input: Civ7SavedConfigIdentity, options?: Civ7DirectControlOptions) =>
    requestCiv7SavedGameConfigurationLoad({ ...input, path: input.fileName }, options),
  reconcileRequiredTargetMod: reconcileCiv7RequiredTargetMod,
  getSetupMapRows: getCiv7SetupMapRows,
  reloadSetupUiInShell: reloadCiv7SetupUiInShell,
  applySinglePlayerSetupIdentity: applyCiv7SinglePlayerSetupIdentity,
  applySinglePlayerSetupOptions: applyCiv7SinglePlayerSetupOptions,
  hostPreparedSinglePlayerGame: hostPreparedCiv7SinglePlayerGame,
  getAppUiSnapshot: getCiv7AppUiSnapshot,
  beginGame: beginCiv7Game,
  checkTunerHealth: checkCiv7TunerHealth,
  getMapSummary: getCiv7MapSummary,
};
